/* ============================================================
   Low-GI Recipes — Lena's own recipe data (EN + UA)
   Source: Website Drafts/low-gi-recipes-draft.md + own photos.
   Categories: main | dessert | baking | snack | bread | sauce
   Diet tags:  sugar-free | gluten-free | low-carb | vegetarian | dairy-free
   ============================================================ */
window.LF_RECIPES = [
  {
    slug: 'beef-skewers-wine-sauce', img: '01-beef-skewers-wine-sauce.jpeg', cat: 'main',
    tags: ['gluten-free', 'low-carb'],
    title: { en: 'Beef Skewers with Red Wine Sauce', ua: 'Шашлики з яловичини з соусом з червоного вина' },
    meta: { prep: { en: '2 hours (incl. marinating)', ua: '2 год (з маринуванням)' }, cook: { en: '20 min', ua: '20 хв' }, serves: { en: 'Serves 2', ua: '2 порції' } },
    why: { en: "Protein-rich beef with non-starchy vegetables keeps blood sugar stable. The sauce uses only a small amount of natural sweetener — swap honey for erythritol to keep GI minimal.", ua: "Яловичина, багата на білок, у поєднанні з некрохмалистими овочами стабілізує рівень цукру в крові. У соусі — мінімум підсолоджувача, а мед можна замінити еритритолом." },
    nutrition: { en: 'Per serving (est.): ~600 kcal · Carbs 14 g · Fat 42 g · Protein 45 g', ua: 'На порцію (прибл.): ~600 ккал · Вуглеводи 14 г · Жири 42 г · Білки 45 г' },
    ingredients: { en: ['400 g beef, cut into small cubes','1 onion, sliced into rings','250 g cherry tomatoes','300 ml dry red wine (150 ml marinade, 150 ml sauce)','1 pinch sea salt','1 pinch ground cinnamon','1 pinch ground chilli','50 g butter','1 tsp almond flour (or 1 tbsp wheat flour)','1 tbsp honey or erythritol','1 tbsp balsamic vinegar'], ua: ['400 г яловичини, нарізаної дрібними шматочками','1 цибулина, нарізана кільцями','250 г помідорів черрі','300 мл сухого червоного вина (150 мл маринад, 150 мл соус)','1 щіпка морської солі','1 щіпка меленої кориці','1 щіпка меленого перцю чилі','50 г вершкового масла','1 ч. л. мигдалевого борошна (або 1 ст. л. пшеничного)','1 ст. л. меду або еритритолу','1 ст. л. бальзамічного оцту'] },
    method: { en: ['Make the marinade: mix salt, honey/erythritol, chilli and cinnamon. Add 150 ml wine. Pour over the beef and marinate for 2 hours (or overnight).','Preheat oven to 180°C fan (200°C without fan).','Slice onion into rings and wash the tomatoes. Remove beef from marinade.','Thread beef, onion and tomatoes alternately onto wooden skewers.','Place on an oven rack and bake for 7–10 minutes until cooked through.','Meanwhile make the sauce: melt butter in a small saucepan over low heat.','Add flour and stir until lightly golden.','Add 150 ml wine gradually, stirring as it comes to a gentle boil.','Add balsamic vinegar, a pinch of cinnamon and chilli. Stir until slightly thickened.','Pour sauce over skewers and serve immediately.'], ua: ['Приготуйте маринад: змішайте сіль, мед/еритритол, чилі та корицю. Додайте 150 мл вина. Залийте м’ясо та маринуйте 2 години (або на ніч).','Розігрійте духовку до 180°C з конвекцією (200°C без).','Наріжте цибулю кільцями та промийте помідори. Вийміть м’ясо з маринаду.','Почергово нанизайте м’ясо, цибулю та помідори на дерев’яні шпажки.','Запікайте на решітці 7–10 хвилин до готовності.','Тим часом приготуйте соус: розтопіть масло в сотейнику на слабкому вогні.','Додайте борошно та помішуйте до легкого золотистого кольору.','Поступово влийте 150 мл вина, помішуючи до легкого закипання.','Додайте бальзамічний оцет, по щіпці кориці та чилі. Помішуйте до легкого загустіння.','Полийте шашлики соусом і подавайте одразу.'] },
    note: { en: 'Replace honey with erythritol and wheat flour with almond flour to reduce the glycaemic impact of the sauce without changing the flavour.', ua: 'Замініть мед еритритолом, а пшеничне борошно — мигдалевим, щоб знизити глікемічний вплив соусу без зміни смаку.' }
  },
  {
    slug: 'lemon-thyme-cookies', img: '02-lemon-thyme-cookies.jpeg', cat: 'snack',
    tags: ['sugar-free', 'gluten-free', 'low-carb', 'vegetarian'],
    title: { en: 'Flour-free Lemon & Thyme Cookies', ua: 'Безборошняне печиво з лимоном та чебрецем' },
    meta: { prep: { en: '5 min + 30 min chilling', ua: '5 хв + 30 хв у холодильнику' }, cook: { en: '7 min', ua: '7 хв' }, serves: { en: 'Makes ~20', ua: '~20 штук' } },
    why: { en: 'Made entirely with almond flour instead of wheat — naturally low in carbohydrates and high in protein and healthy fats. Sweetened with stevia, so no blood sugar spike.', ua: 'Готується виключно на мигдалевому борошні замість пшеничного — мало вуглеводів, багато білка та корисних жирів. Підсолоджено стевією — без стрибків цукру.' },
    nutrition: { en: 'Per cookie (est.): ~100 kcal · Carbs 2 g · Fat 9 g · Protein 3 g', ua: 'На 1 печиво (прибл.): ~100 ккал · Вуглеводи 2 г · Жири 9 г · Білки 3 г' },
    ingredients: { en: ['2 cups (200 g) almond flour','2 eggs','1 tsp vanilla extract','1 tbsp lemon juice','2 tsp lemon zest','1 tsp liquid stevia (or to taste)','¼ cup (60 ml) liquid coconut oil','1 tsp ground flaxseed','Small pinch of fresh or dried thyme'], ua: ['2 склянки (200 г) мигдалевого борошна','2 яйця','1 ч. л. ванільного екстракту','1 ст. л. лимонного соку','2 ч. л. лимонної цедри','1 ч. л. рідкої стевії (за смаком)','¼ склянки (60 мл) рідкої кокосової олії','1 ч. л. меленого льону','Невелика щіпка свіжого або сушеного чебрецю'] },
    method: { en: ['Mix all ingredients together until combined. Refrigerate the dough for 30 minutes.','Preheat oven to 180°C fan. Line a baking tray with baking paper.','Pinch off small pieces and roll into balls — the dough should hold its shape.','Place on the paper and press a few thyme leaves gently into the top of each.','Bake for 5–7 minutes until the edges are just lightly golden. Don’t overbake — they should stay slightly soft.'], ua: ['Змішайте всі інгредієнти. Поставте тісто в холодильник на 30 хвилин.','Розігрійте духовку до 180°C з конвекцією. Застеліть деко пергаментом.','Відщипуйте невеликі шматочки та формуйте кульки — тісто має тримати форму.','Викладіть на пергамент і злегка вдавіть кілька листочків чебрецю зверху.','Випікайте 5–7 хвилин до легкого золотистого краю. Не перетримуйте — печиво має залишатися трохи м’яким.'] },
    note: { en: 'These are low in carbs but high in fat and calories — keep portions to 2–3 cookies at a time.', ua: 'Печиво містить мало вуглеводів, але багато жирів і калорій — оптимальна порція 2–3 штуки.' }
  },
  {
    slug: 'cottage-cheese-poppy-bake', img: '03-cottage-cheese-poppy-bake.jpeg', cat: 'dessert',
    tags: ['sugar-free', 'gluten-free', 'low-carb', 'vegetarian'],
    title: { en: 'Sugar-free Cottage Cheese & Poppy Seed Bake', ua: 'Сирний десерт без цукру з маком' },
    meta: { prep: { en: '10 min', ua: '10 хв' }, cook: { en: '30 min', ua: '30 хв' }, serves: { en: 'Serves 2–3', ua: '2–3 порції' } },
    why: { en: 'High-protein cottage cheese with an almond-and-coconut-flour base — no refined sugar, no white flour. Peanut butter adds healthy fats that slow digestion and steady blood sugar.', ua: 'Сир, багатий на білок, з основою з мигдалевого й кокосового борошна — без цукру та білого борошна. Арахісова паста додає корисні жири, що сповільнюють засвоєння.' },
    nutrition: { en: 'Per serving (est.): ~520 kcal · Carbs 16 g · Fat 40 g · Protein 25 g', ua: 'На порцію (прибл.): ~520 ккал · Вуглеводи 16 г · Жири 40 г · Білки 25 г' },
    ingredients: { en: ['250 g cottage cheese or quark (as dry as possible)','1 egg','1 tsp vanilla','¼ cup almond flour','1 tbsp coconut flour','½ cup natural peanut butter (unsweetened)','2 tbsp Truvia or erythritol','1 tbsp coconut oil (plus extra to grease)','3 tbsp poppy seeds'], ua: ['250 г сиру (кварку), якомога сухішого','1 яйце','1 ч. л. ваніліну','¼ склянки мигдалевого борошна','1 ст. л. кокосового борошна','½ склянки натуральної арахісової пасти (без цукру)','2 ст. л. Truvia або еритритолу','1 ст. л. кокосової олії (плюс для змащування)','3 ст. л. маку'] },
    method: { en: ['Grease a small tin (approx. 300–400 ml) with coconut oil. Preheat oven to 180°C.','Make the base: mix peanut butter with coconut oil and both flours until firm but workable. Add more coconut flour if too runny.','Press the base evenly into the bottom of the tin.','Make the filling: mix cottage cheese, sweetener, vanilla and egg until smooth.','Pour over the base and sprinkle poppy seeds evenly on top.','Bake at 180°C for 20–30 minutes depending on how wet the cheese is. Cool before slicing.'], ua: ['Змастіть невелику форму (300–400 мл) кокосовою олією. Розігрійте духовку до 180°C.','Приготуйте основу: змішайте арахісову пасту з кокосовою олією та обома видами борошна до щільної, але пластичної маси. Додайте кокосового борошна, якщо рідко.','Рівномірно розподіліть основу по дну форми.','Приготуйте начинку: змішайте сир, підсолоджувач, ванілін та яйце до однорідності.','Викладіть поверх основи та рівномірно посипте маком.','Випікайте при 180°C 20–30 хвилин залежно від вологості сиру. Охолодіть перед нарізанням.'] },
    note: { en: 'Use the driest cottage cheese or quark you can find — wetter varieties need a longer bake time.', ua: 'Використовуйте якомога сухіший сир — з вологішим десерт потребуватиме довшого запікання.' }
  },
  {
    slug: 'avocado-ice-cream', img: '04-avocado-ice-cream.jpg', cat: 'dessert',
    tags: ['sugar-free', 'gluten-free', 'low-carb', 'vegetarian', 'dairy-free'],
    title: { en: 'Avocado Ice Cream (No Sugar, 5 Ingredients)', ua: 'Морозиво з авокадо (без цукру, 5 інгредієнтів)' },
    meta: { prep: { en: '10 min', ua: '10 хв' }, cook: { en: 'Freeze 30 min', ua: 'Заморозка 30 хв' }, serves: { en: 'Serves 1–2', ua: '1–2 порції' } },
    why: { en: 'Avocado is one of the lowest-GI fruits — high in healthy monounsaturated fats with virtually no impact on blood sugar. No added sugar, only 5 ingredients.', ua: 'Авокадо — один із фруктів з найнижчим ГІ: багато корисних жирів і майже нульовий вплив на цукор. Без доданого цукру, лише 5 інгредієнтів.' },
    nutrition: { en: 'Per serving (est.): ~120 kcal · Carbs 3 g · Fat 12 g · Protein 1 g', ua: 'На порцію (прибл.): ~120 ккал · Вуглеводи 3 г · Жири 12 г · Білки 1 г' },
    ingredients: { en: ['½ very ripe avocado','1 tbsp lemon juice','1 tsp powdered stevia (to taste)','1 tbsp coconut oil','Small pinch of vanilla'], ua: ['½ дуже стиглого авокадо','1 ст. л. лимонного соку','1 ч. л. стевії в порошку (за смаком)','1 ст. л. кокосової олії','Невелика щіпка ваніліну'] },
    method: { en: ['Blend all ingredients until completely smooth.','Pour into a small container and freeze for 30 minutes.','Remove and shape as desired. If too firm, transfer to the fridge for a few minutes to soften before serving.'], ua: ['Збийте всі інгредієнти у блендері до однорідності.','Перелийте в невелику ємність і заморозьте на 30 хвилин.','Вийміть та сформуйте за бажанням. Якщо надто тверде — потримайте в холодильнику кілька хвилин.'] },
    note: { en: "The avocado disappears completely into the texture — only the pale green colour remains. If you don't like avocado, you won't taste it at all.", ua: 'Смак авокадо у готовому морозиві не відчувається — залишається лише ніжна кремова текстура та блідо-зелений колір.' }
  },
  {
    slug: 'almond-pecan-cookies', img: '05-almond-pecan-cookies.jpeg', cat: 'snack',
    tags: ['sugar-free', 'gluten-free', 'low-carb', 'vegetarian'],
    title: { en: 'Almond & Pecan Cookies (No Flour, No Sugar)', ua: 'Мигдалево-пеканове печиво (без борошна, без цукру)' },
    meta: { prep: { en: '5 min', ua: '5 хв' }, cook: { en: '12 min', ua: '12 хв' }, serves: { en: 'Makes ~15', ua: '~15 штук' } },
    why: { en: 'Pure almond flour base with no refined sugar — sweetened only with erythritol. High in protein and healthy fats, low in carbohydrates. A reliable, fail-proof recipe.', ua: 'Основа — чисте мигдалеве борошно без рафінованого цукру, підсолоджене лише еритритолом. Багато білка та корисних жирів, мало вуглеводів. Простий безвідмовний рецепт.' },
    nutrition: { en: 'Per serving (est.): ~485 kcal · Carbs 10 g · Fat 41 g · Protein 19 g', ua: 'На порцію (прибл.): ~485 ккал · Вуглеводи 10 г · Жири 41 г · Білки 19 г' },
    ingredients: { en: ['200 g almond flour','1 large egg','1 tsp vanilla extract','1 tbsp lime juice (plus zest of ½ lime)','½ tsp bicarbonate of soda','1½ tbsp Truvia or erythritol','A handful of pecan halves (one per cookie)'], ua: ['200 г мигдалевого борошна','1 велике яйце','1 ч. л. ванільного екстракту','1 ст. л. соку лайма (плюс цедра ½ лайма)','½ ч. л. харчової соди','1½ ст. л. Truvia або еритритолу','Жменя горіхів пекан (по одному на печиво)'] },
    method: { en: ['Zest half a lime and squeeze out the juice.','Mix all ingredients together — the dough should be elastic and slightly moist.','Preheat oven to 150°C and line a tray with baking paper.','Scoop out dough and roll into balls. Press one pecan half into the centre of each.','Bake for 10–12 minutes. They firm up as they cool — don’t worry if they seem soft in the oven.'], ua: ['Знімте цедру з половини лайма та видавіть сік.','Змішайте всі інгредієнти — тісто має бути еластичним і трохи вологим.','Розігрійте духовку до 150°C. Застеліть деко пергаментом.','Набирайте тісто та формуйте кульки. У центр кожної вдавіть половинку пекана.','Випікайте 10–12 хвилин. Охолоджуючись, печиво затвердіє.'] },
    note: { en: 'You can use walnut or hazelnut flour instead of almond flour — the result is just as good.', ua: 'Замість мигдалевого борошна можна взяти лісовий або волоський горіх — результат буде таким само вдалим.' }
  },
  {
    slug: 'carrot-cake-philadelphia', img: '06-carrot-cake-philadelphia.jpg', cat: 'dessert',
    tags: ['sugar-free', 'vegetarian'],
    title: { en: 'Carrot Cake with Philadelphia Cream (Sugar-free)', ua: 'Морквяний кекс без цукру з кремом Філадельфія' },
    meta: { prep: { en: '15 min', ua: '15 хв' }, cook: { en: '50 min', ua: '50 хв' }, serves: { en: 'Serves 8–10', ua: '8–10 порцій' } },
    why: { en: 'Wholegrain flour has a lower GI than white; erythritol replaces sugar entirely. Carrots add natural sweetness with fibre, and the Philadelphia frosting is protein-rich with no added sugar.', ua: 'Цільнозернове борошно має нижчий ГІ ніж пшеничне; еритритол замінює цукор. Морква додає природну солодкість і клітковину, а крем Філадельфія — білковий, без цукру.' },
    nutrition: { en: 'Per slice (est.): ~270 kcal · Carbs 18 g · Fat 19 g · Protein 8 g', ua: 'На 1 шматок (прибл.): ~270 ккал · Вуглеводи 18 г · Жири 19 г · Білки 8 г' },
    ingredients: { en: ['— CAKE —','300 g carrot, finely grated','200 g wholegrain wheat flour','65 g erythritol or Truvia','100 g butter, softened','5 eggs','1 tsp cinnamon','½ tsp nutmeg','2 tsp baking powder','1 tsp baking soda','1 tsp salt','1 tsp vanilla extract','— FROSTING —','200 g Philadelphia cream cheese','1 tbsp lemon juice','15 g erythritol or Truvia','½ tsp vanilla extract'], ua: ['— КЕКС —','300 г моркви, дрібно натертої','200 г цільнозернового пшеничного борошна','65 г еритритолу або Truvia','100 г вершкового масла, розм’якшеного','5 яєць','1 ч. л. кориці','½ ч. л. мускатного горіха','2 ч. л. розпушувача','1 ч. л. харчової соди','1 ч. л. солі','1 ч. л. ванільного екстракту','— КРЕМ —','200 г вершкового сиру Філадельфія','1 ст. л. лимонного соку','15 г еритритолу або Truvia','½ ч. л. ванільного екстракту'] },
    method: { en: ['Preheat oven to 180°C. Line a cake tin with parchment.','Beat softened butter with 65 g sweetener and vanilla until light and fluffy.','Add eggs one at a time, mixing well after each.','Sift together flour, cinnamon, nutmeg, baking powder, baking soda and salt. Fold into the wet mixture.','Stir in the grated carrot.','Pour into the tin and bake 40–50 minutes, until a skewer comes out clean. Cool completely before frosting.','For the frosting: beat Philadelphia with lemon juice, 15 g sweetener and vanilla until smooth.','Spread frosting over the cooled cake.'], ua: ['Розігрійте духовку до 180°C. Застеліть форму пергаментом.','Збийте розм’якшене масло з 65 г підсолоджувача та ваніллю до пишності.','Додавайте яйця по одному, добре перемішуючи.','Просійте борошно, корицю, мускатний горіх, розпушувач, соду та сіль. Вмішайте в основну суміш.','Додайте терту моркву та перемішайте.','Вилийте у форму та випікайте 40–50 хвилин (перевірте зубочисткою). Повністю охолодіть.','Для крему: збийте Філадельфію з лимонним соком, 15 г підсолоджувача та ваніллю до гладкості.','Намажте крем на охолоджений кекс.'] }
  },
  {
    slug: 'wholegrain-bread', img: '07-wholegrain-bread.jpeg', cat: 'bread',
    tags: ['sugar-free', 'vegetarian', 'dairy-free'],
    title: { en: 'Wholegrain Sourdough Bread', ua: 'Цільнозерновий хліб на заквасці' },
    meta: { prep: { en: '10 min + 10–16 h proving', ua: '10 хв + 10–16 год вистоювання' }, cook: { en: '40 min', ua: '40 хв' }, serves: { en: '10–12 slices', ua: '10–12 скибок' } },
    why: { en: 'Wholegrain flour retains bran and germ, slowing digestion. Sourdough fermentation further reduces GI compared to regular bread. Flaxseed adds omega-3 and fibre.', ua: 'Цільнозернове борошно зберігає висівки та зародок, уповільнюючи травлення. Ферментація закваски знижує ГІ. Лляне борошно збагачує омега-3 та клітковиною.' },
    nutrition: { en: 'Per slice (est.): ~85 kcal · Carbs 15 g · Fat 1 g · Protein 3 g', ua: 'На 1 скибку (прибл.): ~85 ккал · Вуглеводи 15 г · Жири 1 г · Білки 3 г' },
    ingredients: { en: ['250 g wholegrain wheat flour','20 g flaxseed flour','50 g sourdough starter (active)','5 g salt'], ua: ['250 г цільнозернового пшеничного борошна','20 г борошна з льону','50 г закваски (активної)','5 г солі'] },
    method: { en: ['Combine wholegrain wheat flour and flaxseed flour in a large bowl.','Add the starter and mix, adding a little water gradually until a rough dough forms.','Cover and rest at room temperature for 8–12 hours (overnight is ideal).','Add salt and fold the dough several times. Shape into a loaf.','Prove a further 2–4 hours until noticeably risen.','Preheat oven to 230°C. Bake covered (Dutch oven) for 20 minutes, then uncover and bake 20 minutes more until golden and hollow-sounding.','Cool on a wire rack before slicing — important for texture.'], ua: ['Змішайте цільнозернове та лляне борошно у великій мисці.','Додайте закваску та перемішайте, поступово вливаючи трохи води до утворення тіста.','Накрийте та залиште при кімнатній температурі на 8–12 годин (ідеально на ніч).','Додайте сіль та кілька разів складіть тісто. Сформуйте хлібину.','Залиште підходити ще 2–4 години до помітного збільшення.','Розігрійте духовку до 230°C. Перші 20 хвилин випікайте накритим (чавунець), потім відкрийте ще на 20 хвилин до золотистої скоринки.','Охолодіть на решітці перед нарізанням.'] }
  },
  {
    slug: 'pearl-barley-kutia', img: '08-pearl-barley-kutia.jpeg', cat: 'dessert',
    tags: ['dairy-free', 'vegetarian'],
    title: { en: 'Pearl Barley Kutia (Traditional Ukrainian Dish)', ua: 'Кутя з перлової крупи (традиційна різдвяна)' },
    meta: { prep: { en: '20 min + soaking', ua: '20 хв + замочування' }, cook: { en: '80 min', ua: '80 хв' }, serves: { en: 'Serves 8–10', ua: '8–10 порцій' } },
    why: { en: 'Pearl barley has one of the lowest GI values of all grains (GI ~25), thanks to its rich beta-glucan content. This traditional Ukrainian dish is naturally suited to blood sugar management.', ua: 'Перлова крупа має один із найнижчих ГІ серед зернових (ГІ ~25) завдяки бета-глюкану. Ця традиційна українська страва природно підходить для контролю цукру.' },
    nutrition: { en: 'Per serving (est.): ~400 kcal · Carbs 68 g · Fat 9 g · Protein 9 g', ua: 'На порцію (прибл.): ~400 ккал · Вуглеводи 68 г · Жири 9 г · Білки 9 г' },
    ingredients: { en: ['600 g pearl barley','200 g raisins','100 g walnuts, roughly chopped','50 g poppy seeds','50 g honey or sweetener of choice'], ua: ['600 г перлової крупи','200 г родзинок','100 г волоських горіхів, крупно порубаних','50 г маку','50 г меду або підсолоджувача на вибір'] },
    method: { en: ['Rinse the barley thoroughly and soak in cold water for at least 1 hour (or overnight).','Cook in plenty of salted water for 60–80 minutes until tender. Drain and cool slightly.','Soak raisins in warm water for 10 minutes, then drain.','Pour boiling water over the poppy seeds, drain after 5 minutes, then grind or blend lightly.','Combine the barley with raisins, walnuts, poppy seeds and honey. Mix well.','Taste and adjust sweetness. Serve warm or at room temperature.'], ua: ['Добре промийте крупу та замочіть у холодній воді мінімум на 1 годину (або на ніч).','Варіть у підсоленій воді 60–80 хвилин до м’якості. Злийте воду, злегка охолодіть.','Замочіть родзинки у теплій воді на 10 хвилин, потім злийте.','Залийте мак окропом, через 5 хвилин злийте, злегка перетріть.','З’єднайте кашу з родзинками, горіхами, маком та медом. Добре перемішайте.','Скуштуйте та відрегулюйте солодкість. Подавайте теплою або кімнатної температури.'] }
  },
  {
    slug: 'pumpkin-muffins-halloween', img: '09-pumpkin-muffins-halloween.jpg', cat: 'baking',
    tags: ['sugar-free', 'vegetarian'],
    title: { en: 'Halloween Pumpkin Muffins (Sugar-free)', ua: 'Гарбузові маффіни до Хелловіну (без цукру)' },
    meta: { prep: { en: '10 min', ua: '10 хв' }, cook: { en: '25 min', ua: '25 хв' }, serves: { en: '12 muffins', ua: '12 маффінів' } },
    why: { en: 'Pumpkin purée is low-calorie with a moderate GI. Wholegrain flour and erythritol keep the glycaemic impact low, while cinnamon and ginger support blood sugar regulation.', ua: 'Гарбузове пюре низькокалорійне з помірним ГІ. Цільнозернове борошно та еритритол мінімізують глікемічне навантаження, а кориця й імбир допомагають регуляції цукру.' },
    nutrition: { en: 'Per muffin (est.): ~105 kcal · Carbs 15 g · Fat 3 g · Protein 4 g', ua: 'На 1 маффін (прибл.): ~105 ккал · Вуглеводи 15 г · Жири 3 г · Білки 4 г' },
    ingredients: { en: ['2 cups wholegrain wheat flour','1 tsp gingerbread spice (ginger, cinnamon, clove, allspice)','1½ tsp baking powder','2 eggs','1 cup milk','1 cup pumpkin purée','¼ cup Truvia or erythritol','1 tbsp coconut oil, melted','1 tsp vanilla extract'], ua: ['2 склянки цільнозернового пшеничного борошна','1 ч. л. суміші прянощів для пряників (імбир, кориця, гвоздика, запашний перець)','1½ ч. л. розпушувача','2 яйця','1 склянка молока','1 склянка гарбузового пюре','¼ склянки Truvia або еритритолу','1 ст. л. кокосової олії, розтопленої','1 ч. л. ванільного екстракту'] },
    method: { en: ['Preheat oven to 180°C. Line a muffin tray with paper cases.','Whisk together flour, spice mix and baking powder.','Separately beat eggs, then add milk, pumpkin purée, sweetener, coconut oil and vanilla. Mix well.','Pour wet into dry and stir until just combined — do not over-mix.','Spoon into the cases, filling each about ¾ full.','Bake 20–25 minutes until a skewer comes out clean.','Cool in the tray for 5 minutes, then transfer to a wire rack.'], ua: ['Розігрійте духовку до 180°C. Застеліть форму паперовими вкладишами.','Збийте разом борошно, суміш прянощів та розпушувач.','Окремо збийте яйця, потім додайте молоко, гарбузове пюре, підсолоджувач, кокосову олію та ваніль.','Влийте рідке до сухого та перемішайте до рівномірності — не перемішуйте зайво.','Розкладіть по формах, заповнюючи на ¾.','Випікайте 20–25 хвилин (перевірте зубочисткою).','Охолодіть у формі 5 хвилин, потім перенесіть на решітку.'] }
  },
  {
    slug: 'lime-almond-dessert', img: '10-lime-almond-dessert.jpeg', cat: 'dessert',
    tags: ['sugar-free', 'gluten-free', 'vegetarian'],
    title: { en: 'Lime & Almond Dessert (Sugar-free)', ua: 'Лаймово-мигдалевий десерт (без цукру)' },
    meta: { prep: { en: '10 min', ua: '10 хв' }, cook: { en: '~30 min + chilling', ua: '~30 хв + охолодження' }, serves: { en: 'Serves 8', ua: '8 порцій' } },
    why: { en: 'Coconut and almond flour replace wheat, giving a low-carb, high-fibre base. Bananas provide natural sweetness; Truvia contains no sugar.', ua: 'Кокосове та мигдалеве борошно замінюють пшеничне — низьковуглеводна, багата клітковиною основа. Банани дають природну солодкість; Truvia без цукру.' },
    nutrition: { en: 'Per slice (est.): ~350 kcal · Carbs 17 g · Fat 26 g · Protein 12 g', ua: 'На 1 шматок (прибл.): ~350 ккал · Вуглеводи 17 г · Жири 26 г · Білки 12 г' },
    ingredients: { en: ['½ cup coconut flour','1 tbsp cinnamon','1 tsp baking soda','5 eggs','⅓ cup coconut oil','2 small ripe bananas','1 tbsp vanilla extract','Pinch of sea salt','1 cup almond flour','5 tbsp peanut butter','3 tbsp Truvia or erythritol','2½ limes (zest + juice)','100 g Greek yogurt'], ua: ['½ склянки кокосового борошна','1 ст. л. кориці','1 ч. л. харчової соди','5 яєць','⅓ склянки кокосової олії','2 невеликі стиглі банани','1 ст. л. ванільного екстракту','Дрібка морської солі','1 склянка мигдалевого борошна','5 ст. л. арахісового масла','3 ст. л. Truvia або еритритолу','2½ лайми (цедра + сік)','100 г грецького йогурту'] },
    method: { en: ['Preheat oven to 180°C. Line a tin with parchment, lightly greased.','Mix dry ingredients: coconut flour, cinnamon, baking soda, sea salt.','Blend eggs, mashed bananas, coconut oil, vanilla and juice of 1 lime until smooth.','Combine wet and dry. Pour into the tin and bake about 30 minutes.','Topping: mix almond flour, sweetener, remaining lime juice and peanut butter. Gradually add Greek yogurt to a spreadable consistency.','Trim the baked base if you like; crumble trimmings into the topping.','Spread the yogurt-almond layer over the base.','Scatter almond-peanut crumble on top. Cover and refrigerate — best served the next day.'], ua: ['Розігрійте духовку до 180°C. Застеліть форму пергаментом, злегка змастіть.','Змішайте сухі: кокосове борошно, корицю, соду, сіль.','Збийте яйця, розім’яті банани, кокосову олію, ваніль та сік 1 лайма до однорідності.','З’єднайте суміші. Вилийте у форму та випікайте близько 30 хвилин.','Топінг: змішайте мигдалеве борошно, підсолоджувач, сік решти лаймів та арахісове масло. Поступово додавайте йогурт до пластичності.','За бажання зріжте краї коржа; крихти додайте до топінгу.','Нанесіть йогуртово-мигдалевий шар на корж.','Посипте мигдально-арахісовою крихтою. Накрийте та поставте в холодильник — найсмачніший наступного дня.'] }
  },
  {
    slug: 'avocado-mayonnaise', img: '11-avocado-mayonnaise.jpg', cat: 'sauce',
    tags: ['sugar-free', 'gluten-free', 'low-carb', 'vegetarian'],
    title: { en: 'Avocado Mayonnaise (Sugar-free)', ua: 'Майонез з авокадо (без цукру)' },
    meta: { prep: { en: '1 min', ua: '1 хв' }, cook: { en: '4 min', ua: '4 хв' }, serves: { en: 'Serves 4–6', ua: '4–6 порцій' } },
    why: { en: 'Avocado is rich in monounsaturated fats and has virtually no sugar. This sauce has a GI close to zero — a perfect substitute for shop-bought mayonnaise.', ua: 'Авокадо багатий на корисні жири та майже не містить цукру. ГІ цього соусу близький до нуля — ідеальна заміна магазинному майонезу.' },
    nutrition: { en: 'Per serving (est.): ~60 kcal · Carbs 3 g · Fat 4 g · Protein 2 g', ua: 'На порцію (прибл.): ~60 ккал · Вуглеводи 3 г · Жири 4 г · Білки 2 г' },
    ingredients: { en: ['1 very ripe avocado','2 tsp lemon juice','1 tsp Dijon mustard','½ tsp salt (mustard already contains salt — adjust)','½ tsp dried garlic powder','½ tsp dried onion powder','¼ cup Greek yogurt'], ua: ['1 дуже стиглий авокадо','2 ч. л. лимонного соку','1 ч. л. діжонської гірчиці','½ ч. л. солі (в гірчиці вже є сіль — регулюйте)','½ ч. л. часникового порошку','½ ч. л. цибульного порошку','¼ склянки грецького йогурту'] },
    method: { en: ['Blend avocado with a little Greek yogurt on low speed until smooth.','Add all remaining ingredients and blend on high speed until completely silky.'], ua: ['Збийте авокадо з невеликою кількістю йогурту на малих обертах до однорідності.','Додайте всі інші інгредієнти та збийте на великих обертах до повної гладкості.'] },
    note: { en: 'Store in a sealed glass jar in the fridge for 2–3 days. It darkens slightly — refresh with a splash of lemon juice before serving.', ua: 'Зберігайте в закритій скляній банці в холодильнику 2–3 дні. Соус трохи темніє — перед подачею освіжте лимонним соком.' }
  },
  {
    slug: 'oat-cookies-coconut-sugar', img: '12-oat-cookies-coconut-sugar.jpg', cat: 'baking',
    tags: ['vegetarian'],
    title: { en: 'Oat Cookies with Coconut Sugar', ua: 'Вівсяне печиво на кокосовому цукрі' },
    meta: { prep: { en: '10 min', ua: '10 хв' }, cook: { en: '30 min', ua: '30 хв' }, serves: { en: 'Makes ~18', ua: '~18 штук' } },
    why: { en: 'Coconut sugar has a lower GI than regular sugar (GI ~35 vs 70). Swap for erythritol with a few drops of stevia to reduce GI further. Coarse oats digest slowly, giving lasting energy.', ua: 'Кокосовий цукор має нижчий ГІ ніж звичайний (~35 проти 70). Замініть на еритритол зі стевією для ще нижчого ГІ. Крупні вівсяні пластівці перетравлюються повільно.' },
    nutrition: { en: 'Per cookie (est.): ~110 kcal · Carbs 11 g · Fat 7 g · Protein 2 g', ua: 'На 1 печиво (прибл.): ~110 ккал · Вуглеводи 11 г · Жири 7 г · Білки 2 г' },
    ingredients: { en: ['1 cup rolled oats (coarse / old-fashioned)','1 cup wholegrain wheat flour','⅓ cup coconut sugar (or erythritol for lower GI)','130 g butter or coconut oil','1 egg','Pinch of sea salt','Pinch of baking powder','Pinch of vanilla','Pinch of cinnamon'], ua: ['1 склянка вівсяних пластівців (крупного помелу)','1 склянка цільнозернового пшеничного борошна','⅓ склянки кокосового цукру (або еритритол для нижчого ГІ)','130 г вершкового або кокосового масла','1 яйце','Дрібка морської солі','Дрібка розпушувача','Дрібка ваніліну','Дрібка кориці'] },
    method: { en: ['In a mixer, combine softened butter, egg and coconut sugar on low speed.','Add all remaining ingredients. Use the paddle (not the blade) so the oats stay whole.','Line a baking sheet with parchment. Preheat oven to 190°C.','Refrigerate the dough 10 minutes. Roll into balls and flatten gently with the base of a glass.','Bake 20 minutes until golden. Cool on the tray — cookies firm up as they cool.'], ua: ['У міксері змішайте розм’якшене масло, яйце та кокосовий цукор на малих обертах.','Додайте решту інгредієнтів. Використовуйте лопатку (не ніж), щоб пластівці лишились цілими.','Застеліть деко пергаментом. Розігрійте духовку до 190°C.','Охолодіть тісто 10 хвилин. Скочуйте кульки та приплющуйте дном склянки.','Випікайте 20 хвилин до золотистого кольору. Остигаючи, печиво твердіє.'] }
  },
  {
    slug: 'lemon-cookies-coconut-sugar', img: '13-lemon-cookies-coconut-sugar.jpg', cat: 'baking',
    tags: ['vegetarian', 'dairy-free'],
    title: { en: 'Lemon Cookies with Coconut Sugar', ua: 'Лимонне печиво на кокосовому цукрі' },
    meta: { prep: { en: '10 min + 30 min chilling', ua: '10 хв + 30 хв у холодильнику' }, cook: { en: '15 min', ua: '15 хв' }, serves: { en: 'Makes ~16', ua: '~16 штук' } },
    why: { en: 'A blend of flaxseed flour, coconut flour and wholegrain flour replaces refined white flour. Coconut sugar replaces refined sugar.', ua: 'Суміш лляного, кокосового та цільнозернового борошна замінює рафіноване біле борошно. Кокосовий цукор замінює звичайний.' },
    nutrition: { en: 'Per cookie (est.): ~60 kcal · Carbs 6 g · Fat 3 g · Protein 1 g', ua: 'На 1 печиво (прибл.): ~60 ккал · Вуглеводи 6 г · Жири 3 г · Білки 1 г' },
    ingredients: { en: ['1 tbsp lemon zest','½ cup wholegrain wheat flour','45 g coconut oil or butter','1 tsp baking powder','2 tbsp flaxseed flour','2 tbsp coconut flour','50 g coconut sugar','4 tbsp lemon juice'], ua: ['1 ст. л. лимонної цедри','½ склянки цільнозернового пшеничного борошна','45 г кокосового або вершкового масла','1 ч. л. розпушувача','2 ст. л. борошна з льону','2 ст. л. кокосового борошна','50 г кокосового цукру','4 ст. л. лимонного соку'] },
    method: { en: ['Combine all ingredients in a processor using the paddle (not the blade). The dough will be crumbly and slightly loose.','Refrigerate for 30 minutes. Preheat oven to 180°C towards the end.','Line a baking sheet with parchment.','If still too soft, mix in 1–2 tsp extra flaxseed flour. Roll into balls and flatten with a glass.','Bake for 15 minutes — golden but not burnt.','Cool fully. Cookies firm up significantly as they cool.'], ua: ['Змішайте всі інгредієнти в комбайні лопаткою (не ножем). Тісто буде розсипчастим.','Поставте в холодильник на 30 хвилин. Ближче до кінця розігрійте духовку до 180°C.','Застеліть деко пергаментом.','Якщо тісто м’яке — додайте 1–2 ч. л. лляного борошна. Скочуйте кульки та приплющуйте склянкою.','Випікайте 15 хвилин — золотисті, але не підгорілі.','Повністю охолодіть. Остигаючи, печиво сильно твердіє.'] }
  },
  {
    slug: 'lviv-cheesecake', img: '14-lviv-cheesecake.jpg', cat: 'dessert',
    tags: ['gluten-free', 'vegetarian'],
    title: { en: 'Lviv Cheesecake (Lvivsky Syrnyk)', ua: 'Львівський сирник' },
    meta: { prep: { en: '10 min', ua: '10 хв' }, cook: { en: '20 min + overnight', ua: '20 хв + ніч у холодильнику' }, serves: { en: 'Serves 10–12', ua: '10–12 порцій' } },
    why: { en: 'The base is cottage cheese — high protein, no flour. Coconut flour adds fibre. The chocolate glaze uses cocoa butter and minimal sugar rather than milk chocolate.', ua: 'Основа — кисломолочний сир (білок, без борошна). Кокосове борошно додає клітковину. Шоколадна глазур — з какао-масла та мінімум цукру, без плитки шоколаду.' },
    nutrition: { en: 'Per slice (est.): ~150 kcal · Carbs 14 g · Fat 6 g · Protein 9 g', ua: 'На 1 шматок (прибл.): ~150 ккал · Вуглеводи 14 г · Жири 6 г · Білки 9 г' },
    ingredients: { en: ['— CHEESECAKE —','5 eggs','500 g cottage cheese or quark (squeeze out excess moisture)','1 handful raisins','30 g coconut flour','80 g sugar or sweetener of choice','Pinch of vanilla','1 tsp xanthan gum (optional)','— GLAZE —','1 tbsp cocoa butter','1 tbsp sugar','3 tbsp sour cream','2 tbsp cocoa powder'], ua: ['— СИРНИК —','5 яєць','500 г кисломолочного сиру або кварку (відтиснути зайву вологу)','1 жменя родзинок','30 г кокосового борошна','80 г цукру або підсолоджувача','Дрібка ваніліну','1 ч. л. ксантанової камеді (за бажанням)','— ГЛАЗУР —','1 ст. л. какао-масла','1 ст. л. цукру','3 ст. л. сметани','2 ст. л. какао-порошку'] },
    method: { en: ['Preheat oven to 190°C.','In a mixer with the paddle, combine cottage cheese, eggs, 80 g sugar, vanilla and raisins. Don’t use the blade — you want texture, not a smooth cream.','While mixing, gradually add coconut flour until you get a thick, sticky mass that holds its shape.','Grease a tin and line with parchment.','Transfer to the tin, smooth the top with a fork and bake for 20 minutes.','Cool completely before glazing.','Glaze: melt cocoa butter, then stir in sour cream, sugar and cocoa powder. Pour over immediately — it sets quickly.','Refrigerate overnight. Slice in the morning.'], ua: ['Розігрійте духовку до 190°C.','У міксері з лопаткою змішайте сир, яйця, 80 г цукру, ванілін та родзинки. Ніж не використовуйте — потрібна текстура, а не крем.','Продовжуючи заважати, поступово всипайте кокосове борошно до густої липкої маси.','Змастіть форму та застеліть пергаментом.','Викладіть масу, розрівняйте виделкою та випікайте 20 хвилин.','Повністю охолодіть перед глазур’ю.','Глазур: розтопіть какао-масло, додайте сметану, цукор та какао. Відразу полийте — глазур швидко застигає.','Поставте в холодильник на ніч. Зранку можна їсти.'] }
  },
  {
    slug: 'chocolate-ice-cream', img: '15-chocolate-ice-cream.jpg', cat: 'dessert',
    tags: ['sugar-free', 'gluten-free', 'low-carb', 'vegetarian'],
    title: { en: 'Sugar-free Chocolate Ice Cream', ua: 'Шоколадне морозиво без цукру' },
    meta: { prep: { en: '2 min', ua: '2 хв' }, cook: { en: '8 min + 3 h freezing', ua: '8 хв + 3 год заморозки' }, serves: { en: 'Serves 4', ua: '4 порції' } },
    why: { en: 'Sweetened entirely with stevia (GI = 0). Cocoa butter and butter provide slow-release fat. A blood-sugar-friendly chocolate fix with no added sugar.', ua: 'Підсолоджено виключно стевією (ГІ = 0). Какао-масло та вершкове масло дають повільне вивільнення енергії. Шоколадне задоволення без стрибка цукру.' },
    nutrition: { en: 'Per serving (est.): ~130 kcal · Carbs 2 g · Fat 13 g · Protein 1 g', ua: 'На порцію (прибл.): ~130 ккал · Вуглеводи 2 г · Жири 13 г · Білки 1 г' },
    ingredients: { en: ['30 g cocoa butter','20 g butter','1 tsp liquid stevia (or 2 tbsp honey / sweetener)','½ cup milk','Pinch of vanilla','1 tbsp cocoa powder'], ua: ['30 г какао-масла','20 г вершкового масла','1 ч. л. рідкої стевії (або 2 ст. л. меду / підсолоджувача)','½ склянки молока','Дрібка ваніліну','1 ст. л. какао-порошку'] },
    method: { en: ['Melt cocoa butter in a microwave on full power for 30–40 seconds. If pieces remain, leave 5 minutes to finish melting.','Stir cocoa powder into the melted cocoa butter until completely smooth.','Combine milk, butter, stevia and vanilla, then stir in the cocoa-butter mixture. Mix thoroughly.','Pour into lolly moulds or small containers and freeze for at least 3 hours.'], ua: ['Розтопіть какао-масло в мікрохвильовій печі 30–40 секунд. Якщо лишились шматочки — дайте постояти 5 хвилин.','Додайте какао-порошок та ретельно розмішайте до однорідності.','З’єднайте молоко, масло, стевію та ванілін, потім вмішайте какао-масляну суміш.','Розлийте по формочках і поставте в морозильник мінімум на 3 години.'] }
  },
  {
    slug: 'vegetable-quiche-no-flour', img: '16-vegetable-quiche-no-flour.jpg', cat: 'main',
    tags: ['gluten-free', 'vegetarian'],
    title: { en: 'Vegetable Quiche without Flour', ua: 'Кіш з овочами без борошна' },
    meta: { prep: { en: '2 min', ua: '2 хв' }, cook: { en: '15–23 min', ua: '15–23 хв' }, serves: { en: 'Serves 3', ua: '3 порції' } },
    why: { en: 'No pastry, no flour — the base is egg and flaxseed. Feta adds protein and fat to slow glucose absorption. A light, nutrient-dense meal ready in under 25 minutes.', ua: 'Без тіста та борошна — основа з яєць і лляного борошна. Фета додає білок та жири, сповільнюючи засвоєння глюкози. Легка та поживна страва менш ніж за 25 хвилин.' },
    nutrition: { en: 'Per serving (est.): ~250 kcal · Carbs 26 g · Fat 11 g · Protein 12 g', ua: 'На порцію (прибл.): ~250 ккал · Вуглеводи 26 г · Жири 11 г · Білки 12 г' },
    ingredients: { en: ['6 eggs','2 onions','2 tbsp flaxseed flour','50 g bell pepper','180 g feta cheese','1 garlic clove','1 handful fresh spinach'], ua: ['6 яєць','2 цибулини','2 ст. л. борошна з льону','50 г солодкого перцю','180 г сиру фета','1 зубчик часнику','1 жменя свіжого шпинату'] },
    method: { en: ['Whisk eggs together with flaxseed flour in a large bowl.','Slice onions into rings or half-rings. Crush the garlic.','Add bell pepper, feta and spinach and mix by hand. Crumble the feta or cut into cubes.','Pour into a prepared tin and bake at 180°C for 15 minutes until set and golden on top.'], ua: ['Збийте яйця з лляним борошном виделкою у великій мисці.','Наріжте цибулю кільцями або напівкільцями. Часник пропустіть через давилку.','Додайте перець, фету та шпинат і перемішайте руками. Фету розкришіть або наріжте кубиками.','Вилийте у форму та запікайте при 180°C 15 хвилин до золотистої скоринки.'] }
  },
  {
    slug: 'baked-fish-veg-herbs', img: '17-baked-fish-veg-herbs.jpg', cat: 'main',
    tags: ['gluten-free', 'low-carb', 'dairy-free'],
    title: { en: 'Baked Fish with Vegetables & Herbs', ua: 'Запечена риба з овочами та травами' },
    why: { en: 'Salmon with mushrooms and non-starchy vegetables is a light, protein-rich meal that barely moves blood sugar — a gentle low-GI dinner.', ua: 'Лосось з печерицями та некрохмалистими овочами — легка, багата на білок страва, що майже не впливає на рівень цукру в крові.' },
    nutrition: { en: 'Per serving (est.): ~440 kcal · Carbs 20 g · Fat 24 g · Protein 40 g', ua: 'На порцію (прибл.): ~440 ккал · Вуглеводи 20 г · Жири 24 г · Білки 40 г' },
    meta: { prep: { en: '10 min', ua: '10 хв' }, cook: { en: '35 min', ua: '35 хв' }, serves: { en: 'Serves 2', ua: '2 порції' } },
    ingredients: { en: ['2 salmon fillets','1 onion, sliced','6 medium carrots','10 mushrooms','1 handful fresh herbs (sage, oregano, lemon thyme)','1 pinch sea salt'], ua: ['2 філе лосося','1 цибулина, нарізана','6 середніх морквин','10 печериць','1 жменя свіжих трав (шавлія, орегано, лимонний чебрець)','1 щіпка морської солі'] },
    method: { en: ['Heat the oven to 180°C (or 150°C and double the time).','Scale the fish, rinse and pat dry with kitchen paper. Wash and dry the vegetables.','Arrange everything in a baking dish. Add sage leaves and sprigs of oregano and lemon thyme. Season lightly with salt.','Cover with foil and bake for about 20 minutes, until the fish is cooked through.'], ua: ['Розігрійте духовку до 180°C (або 150°C, подвоївши час).','Очистіть рибу від луски, промийте та обсушіть паперовим рушником. Овочі вимийте та обсушіть.','Викладіть усе у форму. Додайте листочки шавлії, гілочки орегано та лимонного чебрецю. Злегка посоліть.','Накрийте фольгою та запікайте близько 20 хвилин, доки риба не буде готова.'] },
    note: { en: 'Works with any fish and vegetables you have — a simple, forgiving country-style bake.', ua: 'Підходить будь-яка риба та овочі, які є під рукою — проста сільська страва, яку важко зіпсувати.' }
  },
  {
    slug: 'carrot-coriander-soup', img: '18-carrot-coriander-soup.jpg', cat: 'main',
    tags: ['vegetarian', 'dairy-free', 'gluten-free'],
    title: { en: 'Carrot & Coriander Soup', ua: 'Морквяний суп з коріандром' },
    why: { en: 'Carrots and a little sweet potato blended with fresh coriander make a naturally sweet, warming soup — plenty of fibre keeps the rise in blood sugar gentle.', ua: 'Морква з невеликою кількістю батату, збита зі свіжим коріандром, дає природно солодкий, зігрівальний суп — багато клітковини робить підйом цукру м’яким.' },
    nutrition: { en: 'Per serving (est.): ~90 kcal · Carbs 19 g · Fat 0 g · Protein 2 g', ua: 'На порцію (прибл.): ~90 ккал · Вуглеводи 19 г · Жири 0 г · Білки 2 г' },
    meta: { prep: { en: '10 min', ua: '10 хв' }, cook: { en: '50 min', ua: '50 хв' }, serves: { en: 'Serves 6', ua: '6 порцій' } },
    ingredients: { en: ['4 large carrots','2 sweet potatoes','3 garlic cloves','1 pinch sea salt','2 handfuls coriander (cilantro) leaves','2 L water','1 onion'], ua: ['4 великі морквини','2 батати','3 зубчики часнику','1 щіпка морської солі','2 жмені листя коріандру (кінзи)','2 л води','1 цибулина'] },
    method: { en: ['Peel and roughly chop the carrots and sweet potatoes; chop the onion coarsely; peel the garlic.','Bring 2 L water with a pinch of salt to the boil, add the vegetables and simmer for 30 minutes.','Check the vegetables are soft; simmer another 10 minutes if needed, then set aside to cool a little.','Prepare the coriander (remove tough stems, rinse), add to the vegetables and blend until completely smooth.'], ua: ['Очистіть і крупно наріжте моркву та батат; цибулю наріжте крупно; часник очистіть.','Закип’ятіть 2 л води зі щіпкою солі, занурте овочі та варіть 30 хвилин.','Перевірте м’якість овочів; за потреби варіть ще 10 хвилин, потім відставте трохи охолонути.','Підготуйте коріандр (видаліть грубі стебла, промийте), додайте до овочів і пюруйте до однорідності.'] },
    note: { en: 'You can use ordinary potato instead of sweet potato — add a little tomato paste for a touch of sweetness.', ua: 'Замість батату можна взяти звичайну картоплю — додайте трохи томатної пасти для солодкуватого присмаку.' }
  },
  {
    slug: 'birthday-cake-sugar-free', img: '19-birthday-cake-sugar-free.jpg', cat: 'dessert',
    tags: ['sugar-free', 'vegetarian'],
    title: { en: 'Sugar-free Birthday Cake (Blueberry & Lime)', ua: 'Святковий торт без цукру (чорниця й лайм)' },
    why: { en: 'A celebration cake with no refined sugar — wholegrain and almond flour sweetened with erythritol, and coloured naturally with blueberry powder instead of dyes.', ua: 'Святковий торт без рафінованого цукру — цільнозернове й мигдалеве борошно, підсолоджене еритритолом, і природний колір із порошку чорниці замість барвників.' },
    nutrition: { en: 'Per slice (est.): ~350 kcal · Carbs 22 g · Fat 22 g · Protein 16 g', ua: 'На 1 шматок (прибл.): ~350 ккал · Вуглеводи 22 г · Жири 22 г · Білки 16 г' },
    meta: { prep: { en: '30 min', ua: '30 хв' }, cook: { en: '20 min + chilling', ua: '20 хв + охолодження' }, serves: { en: 'Serves 8', ua: '8 порцій' } },
    ingredients: { en: ['— SPONGE —','5 large eggs','1 cup wholegrain wheat flour','1 cup almond flour','2 tsp cocoa butter','1 tbsp lime juice','2 tsp baking powder','1 pinch vanilla','— CREAM —','500 g cream cheese (quark / curd cheese)','½ cup erythritol','2 tbsp lemon zest','1 tbsp blueberry powder','1 handful blueberries'], ua: ['— БІСКВІТ —','5 великих яєць','1 склянка цільнозернового пшеничного борошна','1 склянка мигдалевого борошна','2 ч. л. какао-масла','1 ст. л. соку лайма','2 ч. л. розпушувача','1 щіпка ваніліну','— КРЕМ —','500 г вершкового сиру (кварк)','½ склянки еритритолу','2 ст. л. лимонної цедри','1 ст. л. порошку чорниці','1 жменя чорниці'] },
    method: { en: ['Take the eggs out of the fridge, separate whites and yolks and bring to room temperature. Heat the oven to 150°C. Warm the cocoa butter in the microwave for 20–30 seconds.','Beat the yolks with ¼ cup erythritol and the vanilla until pale and fluffy. Set aside.','Whisk the whites, then fold in the lime juice. Set aside.','Combine the wheat and almond flour with the baking powder.','In one bowl, mix the yolks, the flour mixture and ⅓ of the whites. Mix quickly and briskly into a batter.','Fold in the remaining whites and mix quickly. Divide between prepared tins (greased or lined with baking paper).','Bake at 190°C for 15–20 minutes until golden brown, without opening the door.','While the sponges bake, make the cream: mix 500 g cream cheese with ¼ cup erythritol, a drop of vanilla, lime juice, lemon zest and cocoa butter. Chill.','Cool the sponges. Spread cream on each layer, then over the whole cake. Stir blueberry powder into part of the cream for colour graduations. Decorate with flaked almonds and blueberries.'], ua: ['Дістаньте яйця з холодильника, відділіть білки від жовтків і доведіть до кімнатної температури. Розігрійте духовку до 150°C. Какао-масло підігрійте в мікрохвильовці 20–30 секунд.','Збийте жовтки з ¼ склянки еритритолу та ваніллю до пишної, світлої маси. Відставте.','Збийте білки, потім вмішайте сік лайма. Відставте.','З’єднайте пшеничне й мигдалеве борошно з розпушувачем.','В одній мисці змішайте жовтки, борошняну суміш і ⅓ білків. Швидко й енергійно замісіть тісто.','Влийте решту білків і швидко перемішайте. Розлийте по підготовлених формах (змащених або застелених папером).','Випікайте при 190°C 15–20 хвилин до золотисто-коричневого кольору, не відкриваючи дверцят.','Поки печуться бісквіти, приготуйте крем: змішайте 500 г вершкового сиру з ¼ склянки еритритолу, краплею ванілі, соком лайма, цедрою та какао-маслом. Охолодіть.','Остудіть коржі. Намажте кремом кожен, потім увесь торт. У частину крему додайте порошок чорниці для переходів кольору. Прикрасьте мигдальними пелюстками та чорницею.'] },
    note: { en: 'Add blueberry powder to part of the cream for natural colour, and finish with flaked almonds — a good first-birthday cake.', ua: 'Додайте порошок чорниці в частину крему для природного кольору та прикрасьте мигдальними пелюстками — гарний торт на перший день народження.' }
  },
  {
    slug: 'meat-potato-pie-no-flour', img: '20-meat-potato-pie-no-flour.jpg', cat: 'main',
    tags: ['gluten-free'],
    title: { en: 'Flourless Meat & Potato Pie', ua: 'М’ясний пиріг з картоплею без борошна' },
    why: { en: 'A flax-and-coconut-flour base instead of wheat means far fewer carbs, and the fibre-rich flax with a protein filling keeps blood sugar steadier than a pastry pie.', ua: 'Основа з лляного й кокосового борошна замість пшеничного — значно менше вуглеводів, а багатий на клітковину льон із білковою начинкою тримає цукор стабільнішим, ніж звичайне тісто.' },
    nutrition: { en: 'Per serving (est.): ~380 kcal · Carbs 38 g · Fat 16 g · Protein 22 g', ua: 'На порцію (прибл.): ~380 ккал · Вуглеводи 38 г · Жири 16 г · Білки 22 г' },
    meta: { prep: { en: '10 min', ua: '10 хв' }, cook: { en: '31 min', ua: '31 хв' }, serves: { en: 'Serves 2', ua: '2 порції' } },
    ingredients: { en: ['— BASE —','2 egg whites','½ cup flaxseed flour','2 tbsp coconut flour','1 pinch spices (dried garlic, salt, black pepper)','— FILLING —','2 potatoes','½ cup turkey mince','4 tbsp Greek yogurt','2 tbsp chopped herbs'], ua: ['— ОСНОВА —','2 яєчні білки','½ склянки лляного борошна','2 ст. л. кокосового борошна','1 щіпка спецій (сушений часник, сіль, чорний перець)','— НАЧИНКА —','2 картоплини','½ склянки індичого фаршу','4 ст. л. грецького йогурту','2 ст. л. рубленої зелені'] },
    method: { en: ['For the base, mix the egg whites, flaxseed and coconut flour with dried garlic, salt and black pepper. Mix well.','Prepare the filling: mix the mince with spices.','Press the dough into a 10 cm tin, spreading it out evenly.','Add sliced potato and the mince, and bake for about 15 minutes at 180°C.','Top with the yogurt and scatter over chopped herbs. Turn out once cooled.'], ua: ['Для основи змішайте яєчні білки, лляне й кокосове борошно із сушеним часником, сіллю та чорним перцем. Добре перемішайте.','Приготуйте начинку: змішайте фарш зі спеціями.','Викладіть тісто у форму (10 см), рівномірно розрівняйте.','Додайте нарізану картоплю та фарш і запікайте близько 15 хвилин при 180°C.','Змастіть йогуртом і посипте рубленою зеленню. Виймайте після охолодження.'] },
    note: { en: 'Flax pies are ideal if you want to keep carbs down — vary the filling however you like. Flaxseed flour is high in fibre.', ua: 'Лляні пироги ідеальні, якщо хочете менше вуглеводів — начинку можна змінювати. Лляне борошно багате на клітковину.' }
  },
  {
    slug: 'almond-beetroot-cookies', img: '21-almond-beetroot-cookies.jpg', cat: 'snack',
    tags: ['sugar-free', 'vegetarian', 'dairy-free'],
    title: { en: 'Sugar-free Almond & Beetroot Cookies', ua: 'Мигдально-бурякове печиво без цукру' },
    why: { en: 'Beetroot and banana give these cookies natural colour and sweetness, so no sugar is needed — wholegrain, almond and flax flours keep the glycaemic impact modest.', ua: 'Буряк і банан надають печиву природного кольору й солодкості, тож цукор не потрібен — цільнозернове, мигдалеве та лляне борошно тримають глікемічний вплив помірним.' },
    nutrition: { en: 'Per serving (est.): ~210 kcal · Carbs 17 g · Fat 13 g · Protein 6 g', ua: 'На порцію (прибл.): ~210 ккал · Вуглеводи 17 г · Жири 13 г · Білки 6 г' },
    meta: { prep: { en: '15 min', ua: '15 хв' }, cook: { en: '12 min', ua: '12 хв' }, serves: { en: 'Makes ~8', ua: '~8 штук' } },
    ingredients: { en: ['— COOKIES —','130 g beetroot','1 tbsp liquid coconut oil','1½ cups wholegrain wheat flour','½ cup almond flour','¼ cup flaxseed flour','1 pinch sea salt','1 small banana','— CREAM —','¼ cup raspberries (fresh or frozen)','3 tbsp liquid coconut oil','1 tsp stevia'], ua: ['— ПЕЧИВО —','130 г буряка','1 ст. л. рідкої кокосової олії','1½ склянки цільнозернового пшеничного борошна','½ склянки мигдалевого борошна','¼ склянки лляного борошна','1 щіпка морської солі','1 невеликий банан','— КРЕМ —','¼ склянки малини (свіжої або замороженої)','3 ст. л. рідкої кокосової олії','1 ч. л. стевії'] },
    method: { en: ['Blend the raspberries, 3 tbsp coconut oil and stevia until smooth. Pour into a bowl and chill. Heat the oven to 180°C.','Blend the banana, beetroot and 1 tbsp coconut oil until smooth.','Mix the wheat, flax and almond flour with the salt.','Stir the beetroot mixture into the flour and mix by spoon or hand into a smooth, elastic dough. Add 1 tbsp more coconut oil if needed.','Roll the dough out 6 mm thick and cut out cookies in any shape.','Bake for about 12 minutes (check they are done), then cool completely.','Spread 1 tsp of the cream on each cookie, top with a second and press together.'], ua: ['Збийте малину, 3 ст. л. кокосової олії та стевію до гладкості. Перекладіть у миску та охолодіть. Розігрійте духовку до 180°C.','Збийте банан, буряк і 1 ст. л. кокосової олії до гладкості.','Змішайте пшеничне, лляне та мигдалеве борошно із сіллю.','Вмішайте бурякову масу в борошно ложкою або руками до гладкого еластичного тіста. За потреби додайте ще 1 ст. л. олії.','Розкачайте тісто завтовшки 6 мм і виріжте печиво будь-якої форми.','Випікайте близько 12 хвилин (перевірте готовність), потім повністю охолодіть.','Нанесіть по 1 ч. л. крему на кожне печиво, накрийте другим і притисніть.'] },
    note: { en: 'The pliable, brightly coloured dough is great fun to make with children.', ua: 'Пластичне яскраве тісто чудово підходить для творчості з дітьми.' }
  },
  {
    slug: 'carrot-cake-overnight-oats', img: '22-carrot-cake-overnight-oats.jpg', cat: 'breakfast',
    tags: ['sugar-free', 'vegetarian'],
    title: { en: 'Carrot Cake Overnight Oats', ua: 'Нічна вівсянка «Морквяний кекс»' },
    why: { en: 'Made the night before — oats, chia and grated carrot with cinnamon give slow-release carbs, fibre and omega-3 for a breakfast that keeps energy and blood sugar steady.', ua: 'Готується з вечора — овес, чіа й терта морква з корицею дають повільні вуглеводи, клітковину й омега-3 для сніданку, що тримає енергію та цукор стабільними.' },
    nutrition: { en: 'Per serving (est.): ~260 kcal · Carbs 29 g · Fat 8 g · Protein 19 g', ua: 'На порцію (прибл.): ~260 ккал · Вуглеводи 29 г · Жири 8 г · Білки 19 г' },
    meta: { prep: { en: '10 min + overnight', ua: '10 хв + ніч' }, cook: { en: 'No cook', ua: 'Без готування' }, serves: { en: 'Serves 3', ua: '3 порції' } },
    ingredients: { en: ['450 g Greek yogurt','2 carrots, peeled and grated','5 tbsp chia seeds','3 tsp ground cinnamon','½ cup rolled oats (coarse)','1 handful blueberries','1 tsp stevia','1 pinch vanilla'], ua: ['450 г грецького йогурту','2 морквини, очищені й натерті','5 ст. л. насіння чіа','3 ч. л. меленої кориці','½ склянки вівсяних пластівців (грубих)','1 жменя чорниці','1 ч. л. стевії','1 щіпка ваніліну'] },
    method: { en: ['Mix all the ingredients together and refrigerate overnight.','Before serving, add any berries you like and spoon into a jar or glass.'], ua: ['Змішайте всі інгредієнти та поставте в холодильник на ніч.','Перед подачею додайте будь-які ягоди й перекладіть у баночку або стакан.'] }
  },
  {
    slug: 'apple-pudding-sugar-free', img: '23-apple-pudding-sugar-free.jpg', cat: 'dessert',
    tags: ['sugar-free', 'vegetarian'],
    title: { en: 'Sugar-free Apple Pudding', ua: 'Яблучний пудинг без цукру' },
    why: { en: 'Inspired by English apple sponge — barely any batter, just enough to hold the fruit together, sweetened with erythritol so the apples do the work.', ua: 'Натхненний англійським яблучним бісквітом — мінімум тіста, лише щоб скріпити фрукти, підсолоджено еритритолом, тож головне тут — яблука.' },
    nutrition: { en: 'Per serving (est.): ~90 kcal · Carbs 14 g · Fat 2 g · Protein 3 g', ua: 'На порцію (прибл.): ~90 ккал · Вуглеводи 14 г · Жири 2 г · Білки 3 г' },
    meta: { prep: { en: '5 min', ua: '5 хв' }, cook: { en: '47 min', ua: '47 хв' }, serves: { en: 'Serves 8', ua: '8 порцій' } },
    ingredients: { en: ['9 tbsp wholegrain wheat flour','3 eggs','1½ tbsp coconut flour','½ tsp xanthan gum','½ tsp baking powder','¼ cup erythritol (or 2 tsp honey)','4 apples','1 handful nuts, berries or fruit (optional)','½ cup water','1 pinch ground cinnamon'], ua: ['9 ст. л. цільнозернового пшеничного борошна','3 яйця','1½ ст. л. кокосового борошна','½ ч. л. ксантанової камеді','½ ч. л. розпушувача','¼ склянки еритритолу (або 2 ч. л. меду)','4 яблука','1 жменя горіхів, ягід або фруктів (за бажанням)','½ склянки води','1 щіпка меленої кориці'] },
    method: { en: ['Heat the oven to 180°C and grease a tin with a thin layer of oil.','Mix all the batter ingredients (except the apples and fruit). Stir with a spoon first, then whisk.','Let the batter rest to check it thickens; add a little water if needed. Cut the apples into pieces.','Mix the apples with the erythritol (or honey / sweetener).','Put the apples in the tin, pour over the batter and dust with cinnamon. Bake for 20 minutes.','Decorate the pudding with berries, nuts or a little sour cream.'], ua: ['Розігрійте духовку до 180°C і змастіть форму тонким шаром олії.','Змішайте всі інгредієнти для тіста (крім яблук і фруктів). Спочатку перемішайте ложкою, потім збийте вінчиком.','Дайте тісту постояти, щоб перевірити набухання; за потреби додайте трохи води. Наріжте яблука шматочками.','Змішайте яблука з еритритолом (або медом / підсолоджувачем).','Викладіть яблука у форму, залийте тістом і посипте корицею. Випікайте 20 хвилин.','Прикрасьте пудинг ягодами, горіхами або сметаною.'] }
  },
  {
    slug: 'lemon-slices-sugar-free', img: '24-lemon-slices-sugar-free.jpg', cat: 'dessert',
    tags: ['sugar-free', 'gluten-free', 'low-carb', 'vegetarian'],
    title: { en: 'Sugar-free Lemon Slices (Gluten-free)', ua: 'Лимонні тістечка без цукру та глютену' },
    why: { en: 'A keto-friendly lemon slice — an almond-flour base with a silky lemon-curd top, sweetened with erythritol. Rich, so a small piece satisfies without spiking blood sugar.', ua: 'Кето-тістечко з лимоном — мигдалева основа та шовковистий лимонний крем, підсолоджені еритритолом. Ситне, тож маленького шматочка достатньо без стрибка цукру.' },
    nutrition: { en: 'Per slice (est.): ~215 kcal · Carbs 3 g · Fat 21 g · Protein 4 g', ua: 'На 1 шматок (прибл.): ~215 ккал · Вуглеводи 3 г · Жири 21 г · Білки 4 г' },
    meta: { prep: { en: '10 min', ua: '10 хв' }, cook: { en: '37 min', ua: '37 хв' }, serves: { en: 'Makes ~16', ua: '~16 штук' } },
    ingredients: { en: ['— ALMOND BASE —','6 tbsp coconut oil','1¾ cups almond flour','¼ cup erythritol','1 tbsp lemon zest','— LEMON TOP —','½ cup liquid coconut oil','¼ cup erythritol with stevia (Truvia)','3 tbsp lemon zest','½ cup lemon juice','6 egg yolks','½ tsp xanthan gum','1 tbsp gelatine (softened in water)'], ua: ['— МИГДАЛЕВА ОСНОВА —','6 ст. л. кокосової олії','1¾ склянки мигдалевого борошна','¼ склянки еритритолу','1 ст. л. лимонної цедри','— ЛИМОННИЙ ШАР —','½ склянки рідкої кокосової олії','¼ склянки еритритолу зі стевією (Truvia)','3 ст. л. лимонної цедри','½ склянки лимонного соку','6 яєчних жовтків','½ ч. л. ксантанової камеді','1 ст. л. желатину (замоченого у воді)'] },
    method: { en: ['Heat the oven to 180°C. For the base, mix the coconut oil, almond flour, erythritol and lemon zest.','Line or grease a tin and press the base in as an even, firm layer. Bake for 10 minutes, then leave to cool a little.','For the topping, warm the coconut oil gently in a pan.','Dissolve the erythritol in a little water, then mix with the oil, lemon juice, zest and yolks. Return to the heat.','Stir until thickened, then pour into a tall jug.','Blend with the xanthan gum and softened gelatine until smooth.','Pour over the almond base, spread out and bake for 10 minutes at 180°C.','Cool before slicing. Dust with almond or coconut flour, or a little sweetener, to serve.'], ua: ['Розігрійте духовку до 180°C. Для основи змішайте кокосову олію, мигдалеве борошно, еритритол і лимонну цедру.','Застеліть або змастіть форму та викладіть основу рівним щільним шаром. Випікайте 10 хвилин, потім трохи охолодіть.','Для верху злегка підігрійте кокосову олію в сотейнику.','Розчиніть еритритол у невеликій кількості води, змішайте з олією, лимонним соком, цедрою та жовтками. Поверніть на вогонь.','Помішуйте до загустіння, потім перелийте у високий стакан.','Збийте з ксантановою камеддю та замоченим желатином до гладкості.','Вилийте на мигдалеву основу, розрівняйте та запікайте 10 хвилин при 180°C.','Охолодіть перед нарізанням. При подачі посипте мигдалевим чи кокосовим борошном або підсолоджувачем.'] },
    note: { en: 'Rich and calorific — a tiny piece goes a long way.', ua: 'Ситне й калорійне — маленького шматочка вистачає надовго.' }
  },
  {
    slug: 'gingerbread-cookies', img: '25-gingerbread-cookies.jpg', cat: 'baking',
    tags: ['vegetarian', 'dairy-free'],
    title: { en: 'Christmas Gingerbread Cookies (No Refined Sugar)', ua: 'Різдвяне імбирне печиво без цукру' },
    why: { en: 'Warmly spiced gingerbread with no refined sugar — a little honey and stevia for sweetness, with flax and coconut flour to soften the glycaemic hit. Decorate with the sugar-free icing.', ua: 'Ароматне імбирне печиво без рафінованого цукру — трохи меду й стевії для солодкості, а лляне й кокосове борошно пом’якшують глікемічний вплив. Прикрасьте глазур’ю без цукру.' },
    nutrition: { en: 'Per cookie (est.): ~135 kcal · Carbs 14 g · Fat 8 g · Protein 2 g', ua: 'На 1 печиво (прибл.): ~135 ккал · Вуглеводи 14 г · Жири 8 г · Білки 2 г' },
    meta: { prep: { en: '5 min + 30 min chilling', ua: '5 хв + 30 хв у холодильнику' }, cook: { en: '10 min', ua: '10 хв' }, serves: { en: 'Makes ~5 large', ua: '~5 великих' } },
    ingredients: { en: ['— GINGERBREAD —','1 tbsp ginger (dried, or fresh finely grated)','45 g coconut oil or butter','1 tsp vanilla extract','2 tsp stevia','1½ tbsp honey','2 tbsp flaxseed flour','2 tbsp coconut flour','1 tbsp water','½ cup wholegrain wheat flour','1 tsp baking powder','— ICING —','4 tbsp powdered erythritol','1 egg white','1 tsp xanthan gum','3 tsp lemon juice','1 pinch vanilla'], ua: ['— ПЕЧИВО —','1 ст. л. імбиру (сухого або свіжого дрібно натертого)','45 г кокосової олії або вершкового масла','1 ч. л. ванільного екстракту','2 ч. л. стевії','1½ ст. л. меду','2 ст. л. лляного борошна','2 ст. л. кокосового борошна','1 ст. л. води','½ склянки цільнозернового пшеничного борошна','1 ч. л. розпушувача','— ГЛАЗУР —','4 ст. л. пудри з еритритолу','1 яєчний білок','1 ч. л. ксантанової камеді','3 ч. л. лимонного соку','1 щіпка ваніліну'] },
    method: { en: ['Mix all the gingerbread ingredients and form a ball. Chill for about 30 minutes (a blender or food processor helps, or just use your hands).','Heat the oven to 150°C and take the dough out of the fridge.','Roll out on cling film or baking paper (dust with a little flour). Roll 3–4 mm thick and cut out shapes.','Bake at 150°C for about 10 minutes. They may stay slightly moist inside but firm up as they cool.','Cool (faster on a cold plate); after 10–15 minutes they are ready to ice.','For the icing, mix the powdered erythritol, vanilla and xanthan gum well.','Whisk the egg white on low until softly whipped and white, then add the lemon juice.','Combine, gradually adding the white, to a firm piping consistency. Chill. Colour part with a little cocoa if you like.','Pipe patterns onto the cookies and leave to dry overnight — the icing sets firm.'], ua: ['Змішайте всі інгредієнти для печива та сформуйте кульку. Охолодіть близько 30 хвилин (можна блендером чи комбайном або просто руками).','Розігрійте духовку до 150°C і дістаньте тісто з холодильника.','Розкачайте на плівці чи папері (присипте трохи борошном). Товщина 3–4 мм, виріжте фігурки.','Випікайте при 150°C близько 10 хвилин. Усередині може лишатися трохи вологи, але після охолодження затвердіє.','Охолодіть (швидше на холодній тарілці); за 10–15 хвилин можна наносити глазур.','Для глазурі добре змішайте пудру з еритритолу, ваніль і ксантанову камідь.','Збийте яєчний білок на низьких обертах до легкої, білої піни, потім додайте лимонний сік.','З’єднайте, поступово додаючи білок, до щільної консистенції для нанесення. Охолодіть. За бажанням частину підфарбуйте какао.','Нанесіть візерунки на печиво та залиште сохнути на ніч — глазур добре застигає.'] },
    note: { en: 'Great as edible gifts or tree decorations.', ua: 'Чудові як їстівні подарунки або ялинкові прикраси.' }
  },
  {
    slug: 'chocolate-ginger-cake-avocado-cream', img: '26-chocolate-ginger-cake-avocado-cream.jpg', cat: 'dessert',
    tags: ['sugar-free', 'vegetarian'],
    title: { en: 'Chocolate-Ginger Cake with Avocado Cream', ua: 'Шоколадно-імбирний кекс з кремом з авокадо' },
    why: { en: 'A festive vegetarian chocolate-and-ginger sponge with no sugar, topped with a naturally green avocado-and-kiwi cream sweetened with stevia. Fresh ginger and cocoa with almost no added sugar keep it gentle on blood sugar.', ua: 'Святковий вегетаріанський шоколадно-імбирний бісквіт без цукру з природно зеленим кремом з авокадо й ківі, підсолодженим стевією. Свіжий імбир і какао майже без цукру роблять його м’яким для рівня цукру.' },
    nutrition: { en: 'Per serving (est.): ~155 kcal · Carbs 10 g · Fat 12 g · Protein 2 g', ua: 'На порцію (прибл.): ~155 ккал · Вуглеводи 10 г · Жири 12 г · Білки 2 г' },
    meta: { prep: { en: '10 min', ua: '10 хв' }, cook: { en: '25 min', ua: '25 хв' }, serves: { en: 'Serves 6', ua: '6 порцій' } },
    ingredients: { en: ['— CAKE —','1 cup water','1 tbsp coconut flour','½ cup wholegrain wheat flour','1 tbsp flaxseed flour','1 tbsp cocoa','1 tbsp fresh ginger, peeled','1 tsp baking powder','½ tsp stevia','1 pinch vanilla','1 pinch ground cinnamon','40 g coconut oil or butter','— AVOCADO CREAM —','1 very ripe avocado','1 kiwi','1 tsp stevia','1 pinch vanilla','1 tsp xanthan gum','1 tbsp coconut oil'], ua: ['— КЕКС —','1 склянка води','1 ст. л. кокосового борошна','½ склянки цільнозернового пшеничного борошна','1 ст. л. лляного борошна','1 ст. л. какао','1 ст. л. свіжого імбиру, очищеного','1 ч. л. розпушувача','½ ч. л. стевії','1 щіпка ваніліну','1 щіпка меленої кориці','40 г кокосової олії або вершкового масла','— КРЕМ З АВОКАДО —','1 дуже стигле авокадо','1 ківі','1 ч. л. стевії','1 щіпка ваніліну','1 ч. л. ксантанової камеді','1 ст. л. кокосової олії'] },
    method: { en: ['Prepare a 24 cm tin lined with a circle of parchment. Heat the oven to 180°C.','Blend all the cake ingredients into a batter, adding the baking powder last.','Pour into the tin and bake for 10–15 minutes, then cool completely and cut out shapes with a cutter.','For the cream, blend all the cream ingredients until smooth.','Firm up the cream in the freezer for 10–15 minutes, checking and stirring to the right consistency.','Spread thickly over the sponge, pipe a pattern, and chill to soak. Use the cream just before serving as the colour changes on storage.'], ua: ['Підготуйте форму 24 см, застеливши дно кружком пергаменту. Розігрійте духовку до 180°C.','Збийте всі інгредієнти кексу в тісто, додаючи розпушувач останнім.','Вилийте у форму та випікайте 10–15 хвилин, потім повністю охолодіть і виріжте фігурки каттером.','Для крему збийте всі інгредієнти до гладкості.','Загустіть крем у морозилці 10–15 хвилин, перевіряючи й помішуючи до потрібної консистенції.','Намажте товстим шаром на бісквіт, зробіть візерунок і поставте в холодильник просочитися. Використовуйте крем перед подачею, бо колір змінюється при зберіганні.'] },
    note: { en: 'Use a ripe, soft avocado and finish with the cream just before serving — the green colour is brightest fresh.', ua: 'Візьміть стигле м’яке авокадо та наносьте крем перед подачею — зелений колір найяскравіший свіжим.' }
  },
  {
    slug: 'oat-pancakes-plums', img: '27-oat-pancakes-plums.jpg', cat: 'breakfast',
    tags: ['sugar-free', 'vegetarian'],
    title: { en: 'Oat Pancakes with Stewed Plums', ua: 'Вівсяні млинці з тушкованими сливами' },
    why: { en: 'Wholegrain oats and flax make fibre-rich pancakes with slow-release carbs; plums add natural sweetness, so only a pinch of stevia is needed — a steadier start than white-flour pancakes.', ua: 'Цільний овес і льон дають багаті на клітковину млинці з повільними вуглеводами; сливи додають природної солодкості, тож потрібна лише щіпка стевії — стабільніший початок дня, ніж млинці з білого борошна.' },
    nutrition: { en: 'Per serving (est.): ~105 kcal · Carbs 13 g · Fat 4 g · Protein 4 g', ua: 'На порцію (прибл.): ~105 ккал · Вуглеводи 13 г · Жири 4 г · Білки 4 г' },
    meta: { prep: { en: '10 min', ua: '10 хв' }, cook: { en: '37 min', ua: '37 хв' }, serves: { en: 'Serves 6', ua: '6 порцій' } },
    ingredients: { en: ['1 cup rolled oats','½ cup water','2 tbsp flaxseed flour','2 eggs','1 pinch stevia','1 tsp baking powder','2 plums'], ua: ['1 склянка вівсяних пластівців','½ склянки води','2 ст. л. лляного борошна','2 яйця','1 щіпка стевії','1 ч. л. розпушувача','2 сливи'] },
    method: { en: ['Mix all the batter ingredients and stir until combined. Leave to swell for about 15 minutes.','Grease a pan with coconut or butter and heat over medium.','Fry the pancakes until done on both sides.','Slice the plums and fry them in the pan.','Top the pancakes with the plums and dust with erythritol.'], ua: ['Змішайте всі інгредієнти тіста та перемішайте до однорідності. Залиште набухнути близько 15 хвилин.','Змастіть сковороду кокосовою або вершковою олією та розігрійте на середньому вогні.','Смажте млинці до готовності з обох боків.','Наріжте сливи дольками та підсмажте на сковороді.','Викладіть сливи на млинці та посипте еритритолом.'] }
  },
  {
    slug: 'meatballs-mandarin-herbs', img: '28-meatballs-mandarin-herbs.jpg', cat: 'main',
    tags: ['gluten-free', 'dairy-free', 'low-carb'],
    title: { en: 'Meatballs with Mandarin & Herbs', ua: 'Фрикадельки з мандаринами та травами' },
    why: { en: 'Protein-rich meatballs bound with flax and ground nuts instead of breadcrumbs — the mandarin segments add a little natural sweetness without moving blood sugar much.', ua: 'Багаті на білок фрикадельки, скріплені льоном і меленими горіхами замість панірувальних сухарів — дольки мандарина додають трохи природної солодкості, майже не впливаючи на цукор.' },
    nutrition: { en: 'Per serving (est.): ~280 kcal · Carbs 2 g · Fat 18 g · Protein 28 g', ua: 'На порцію (прибл.): ~280 ккал · Вуглеводи 2 г · Жири 18 г · Білки 28 г' },
    meta: { prep: { en: '10 min', ua: '10 хв' }, cook: { en: '30 min', ua: '30 хв' }, serves: { en: 'Serves 5', ua: '5 порцій' } },
    ingredients: { en: ['700 g mince','3 garlic cloves','2 tbsp flaxseed meal','1 tbsp ground nuts','1 tbsp sea salt','1 tbsp herbes de Provence','2 mandarins'], ua: ['700 г фаршу','3 зубчики часнику','2 ст. л. лляного шроту','1 ст. л. мелених горіхів','1 ст. л. морської солі','1 ст. л. прованських трав','2 мандарини'] },
    method: { en: ['Heat the oven to 180°C.','Finely chop the garlic and mix with the mince, herbs, flax and nut flour, and salt.','Peel the mandarins and separate into segments.','With wet hands, form small balls, place in a dish and tuck the mandarin segments between them.','Bake for 10–15 minutes until cooked through.'], ua: ['Розігрійте духовку до 180°C.','Дрібно наріжте часник і змішайте з фаршем, травами, лляним та горіховим борошном і сіллю.','Очистіть мандарини та розділіть на дольки.','Вологими руками сформуйте невеликі кульки, викладіть у форму та розкладіть між ними дольки мандарина.','Запікайте 10–15 хвилин до готовності.'] },
    note: { en: 'The mandarin pairing was Lena’s husband’s idea — meat with a little citrus works beautifully.', ua: 'Поєднання з мандаринами придумав чоловік Олени — м’ясо з цитрусом смакує чудово.' }
  },
  {
    slug: 'blueberry-curd-tart', img: '29-blueberry-curd-tart.jpg', cat: 'dessert',
    tags: ['sugar-free', 'gluten-free', 'low-carb', 'vegetarian'],
    title: { en: 'Low-carb Blueberry Curd Tart', ua: 'Низьковуглеводний тарт з чорничним курдом' },
    why: { en: 'A coconut-and-flax crust with a homemade blueberry curd, sweetened only with erythritol — low in carbs and gentle on blood sugar.', ua: 'Основа з кокосового й лляного борошна з домашнім чорничним курдом, підсолодженим лише еритритолом — мало вуглеводів і м’яко для рівня цукру.' },
    nutrition: { en: 'Per serving (est.): ~190 kcal · Carbs 3 g · Fat 17 g · Protein 6 g', ua: 'На порцію (прибл.): ~190 ккал · Вуглеводи 3 г · Жири 17 г · Білки 6 г' },
    meta: { prep: { en: '5 min', ua: '5 хв' }, cook: { en: '48 min', ua: '48 хв' }, serves: { en: 'Serves 3', ua: '3 порції' } },
    ingredients: { en: ['— CRUST —','¼ cup coconut flour','¼ cup erythritol','¼ cup flaxseed flour','3 egg whites','30 g coconut oil','— CURD —','3 egg yolks','40 g erythritol','1 pinch vanilla','1 handful blueberries'], ua: ['— ОСНОВА —','¼ склянки кокосового борошна','¼ склянки еритритолу','¼ склянки лляного борошна','3 яєчні білки','30 г кокосової олії','— КУРД —','3 яєчні жовтки','40 г еритритолу','1 щіпка ваніліну','1 жменя чорниці'] },
    method: { en: ['Mix the crust ingredients. Heat the oven to 180°C and grease a 20 cm tin.','Press the dough over the base with a border, prick with a fork and bake about 15 minutes until set.','Blend the blueberries to a purée.','Mix with the egg yolks, erythritol and vanilla, and heat gently, stirring constantly, until thickened. Cool in the freezer.','Cool the baked tart and carefully remove it. Fill with the curd, top with berries and chill until set.'], ua: ['Змішайте інгредієнти основи. Розігрійте духовку до 180°C і змастіть форму 20 см.','Викладіть тісто по дну з бортиком, наколіть виделкою та випікайте близько 15 хвилин до готовності.','Збийте чорницю в пюре.','Змішайте з жовтками, еритритолом і ваніллю та прогрійте на слабкому вогні, постійно помішуючи, до загустіння. Охолодіть у морозилці.','Охолодіть спечений тарт і обережно вийміть. Наповніть курдом, прикрасьте ягодами та охолодіть до застигання.'] }
  },
  {
    slug: 'pumpkin-oat-pancakes-chocolate', img: '30-pumpkin-oat-pancakes-chocolate.jpg', cat: 'breakfast',
    tags: ['vegetarian', 'dairy-free'],
    title: { en: 'Pumpkin Oat Pancakes with Chocolate Sauce', ua: 'Гарбузово-вівсяні млинці з шоколадом' },
    why: { en: 'Pumpkin and oat-flour pancakes with a cocoa sauce sweetened with isomalt — a warming autumn breakfast with fibre and no refined sugar.', ua: 'Млинці з гарбуза й вівсяного борошна з какао-соусом на ізомальті — зігрівальний осінній сніданок із клітковиною й без рафінованого цукру.' },
    nutrition: { en: 'Per serving (est.): ~130 kcal · Carbs 18 g · Fat 4 g · Protein 6 g', ua: 'На порцію (прибл.): ~130 ккал · Вуглеводи 18 г · Жири 4 г · Білки 6 г' },
    meta: { prep: { en: '3 min', ua: '3 хв' }, cook: { en: '15 min', ua: '15 хв' }, serves: { en: 'Serves 3', ua: '3 порції' } },
    ingredients: { en: ['1 cup water','2 eggs','½–¾ cup oat flour','1 tbsp coconut flour','1 tsp baking powder','1 pinch salt','1 tsp stevia','2–3 tbsp pumpkin purée','1 tsp cinnamon','1 pinch vanilla','1 heaped tbsp cocoa (fat-reduced)','2 tbsp isomalt','2 tsp water'], ua: ['1 склянка води','2 яйця','½–¾ склянки вівсяного борошна','1 ст. л. кокосового борошна','1 ч. л. розпушувача','1 щіпка солі','1 ч. л. стевії','2–3 ст. л. гарбузового пюре','1 ч. л. кориці','1 щіпка ваніліну','1 ст. л. з горою какао (знежиреного)','2 ст. л. ізомальту','2 ч. л. води'] },
    method: { en: ['Mix the dry and wet ingredients separately.','Combine, adding a little water for the right consistency.','Let the batter swell.','Pour onto a hot pan and fry both sides.','Make the sauce from cocoa and isomalt with water over the heat.','Drizzle over the pancakes, scatter with nuts and stack.'], ua: ['Змішайте окремо сухі та вологі інгредієнти.','З’єднайте, додаючи трохи води для потрібної консистенції.','Дайте тісту набухнути.','Вилийте на гарячу сковороду та смажте з обох боків.','Приготуйте соус із какао та ізомальту з водою на вогні.','Полийте млинці соусом, посипте горіхами та складіть стопкою.'] }
  },
  {
    slug: 'dried-fruit-sweets', img: '31-dried-fruit-sweets.jpg', cat: 'snack',
    tags: ['vegetarian', 'dairy-free', 'gluten-free'],
    title: { en: 'No-bake Dried Fruit Sweets', ua: 'Цукерки із сухофруктів' },
    why: { en: 'Blended dried fruit rolled in seeds and cocoa — a simple whole-food sweet with fibre. Naturally sugary from the fruit, so best enjoyed in small amounts.', ua: 'Збиті сухофрукти, обкачані в насінні та какао — проста натуральна солодкість із клітковиною. Через фрукти вони солодкі, тож найкраще їсти потроху.' },
    nutrition: { en: 'Per serving (est.): ~120 kcal · Carbs 24 g · Fat 3 g · Protein 2 g', ua: 'На порцію (прибл.): ~120 ккал · Вуглеводи 24 г · Жири 3 г · Білки 2 г' },
    meta: { prep: { en: '3 min', ua: '3 хв' }, cook: { en: 'No bake', ua: 'Без випікання' }, serves: { en: 'Serves 2', ua: '2 порції' } },
    ingredients: { en: ['1 handful dried fruit','20 g water','20 g coating (sesame, cocoa, almond flour, barley powder)'], ua: ['1 жменя сухофруктів','20 г води','20 г обсипки (кунжут, какао, мигдалеве борошно, порошок ячменю)'] },
    method: { en: ['Blend the dried fruit, adding a little water if needed.','Scoop out the thick mixture, form into balls and roll in the coating.','Eat straight away, or chill well first.'], ua: ['Перемеліть сухофрукти в блендері, за потреби додайте трохи води.','Ложкою набирайте густу масу, формуйте кульки та обкачуйте в обсипці.','Їжте одразу або добре охолодіть.'] }
  },
  {
    slug: 'rabbit-rosemary', img: '32-rabbit-rosemary.jpg', cat: 'main',
    tags: ['gluten-free', 'dairy-free', 'low-carb'],
    title: { en: 'Rabbit with Rosemary', ua: 'Кролик з розмарином' },
    why: { en: 'Lean rabbit is a light, low-fat protein; roasted slowly with vegetables and rosemary it makes a gentle, low-GI dinner — good for children and dietary eating.', ua: 'Пісний кролик — легкий, нежирний білок; повільно запечений з овочами й розмарином, дає м’яку вечерю з низьким ГІ — підходить дітям і дієтичному харчуванню.' },
    nutrition: { en: 'Per serving (est.): ~300 kcal · Carbs 10 g · Fat 10 g · Protein 42 g', ua: 'На порцію (прибл.): ~300 ккал · Вуглеводи 10 г · Жири 10 г · Білки 42 г' },
    meta: { prep: { en: '5 min', ua: '5 хв' }, cook: { en: '1 h 10 min', ua: '1 год 10 хв' }, serves: { en: 'Serves 2', ua: '2 порції' } },
    ingredients: { en: ['1 rabbit, jointed','1 cup mixed vegetables','Salad dressing / juices, to taste','Olive oil, to taste','1 handful rosemary'], ua: ['1 кролик, порційно нарізаний','1 склянка овочів (асорті)','Заправка / сік від салату, за смаком','Оливкова олія, за смаком','1 жменя розмарину'] },
    method: { en: ['Lay the vegetables in the bottom of a dish.','Pour over the salad juices and olive oil and add the rosemary.','Roast at 180°C for about an hour, covered with foil so it stays tender — supper is ready.'], ua: ['Викладіть овочі на дно форми.','Полийте соком від салату та оливковою олією, додайте розмарин.','Запікайте при 180°C близько години під фольгою, щоб м’ясо протушилося — вечеря готова.'] }
  }
];
