/* ============================================================
   Low-GI Recipes — Lena's own recipe data (EN + UA)
   Source: Website Drafts/low-gi-recipes-draft.md + own photos.
   Categories: main | dessert | baking | snack | bread | sauce
   Diet tags:  sugar-free | gluten-free | low-carb | vegetarian | dairy-free
   ============================================================ */
window.LF_RECIPES = [
  {
    slug: 'beef-skewers-wine-sauce', img: '01-beef-skewers-wine-sauce.jpeg', cat: 'main',
    tags: ['gluten-free', 'low-carb'],
    title: { en: 'Beef Skewers with Red Wine Sauce', ua: 'Шашлики з яловичини з соусом з червоного вина' },
    meta: { prep: { en: '2 hours (incl. marinating)', ua: '2 год (з маринуванням)' }, cook: { en: '20 min', ua: '20 хв' }, serves: { en: 'Serves 2', ua: '2 порції' } },
    why: { en: "Protein-rich beef with non-starchy vegetables keeps blood sugar stable. The sauce uses only a small amount of natural sweetener — swap honey for erythritol to keep GI minimal.", ua: "Яловичина, багата на білок, у поєднанні з некрохмалистими овочами стабілізує рівень цукру в крові. У соусі — мінімум підсолоджувача, а мед можна замінити еритритолом." },
    ingredients: { en: ['400 g beef, cut into small cubes','1 onion, sliced into rings','250 g cherry tomatoes','300 ml dry red wine (150 ml marinade, 150 ml sauce)','1 pinch sea salt','1 pinch ground cinnamon','1 pinch ground chilli','50 g butter','1 tsp almond flour (or 1 tbsp wheat flour)','1 tbsp honey or erythritol','1 tbsp balsamic vinegar'], ua: ['400 г яловичини, нарізаної дрібними шматочками','1 цибулина, нарізана кільцями','250 г помідорів черрі','300 мл сухого червоного вина (150 мл маринад, 150 мл соус)','1 щіпка морської солі','1 щіпка меленої кориці','1 щіпка меленого перцю чилі','50 г вершкового масла','1 ч. л. мигдалевого борошна (або 1 ст. л. пшеничного)','1 ст. л. меду або еритритолу','1 ст. л. бальзамічного оцту'] },
    method: { en: ['Make the marinade: mix salt, honey/erythritol, chilli and cinnamon. Add 150 ml wine. Pour over the beef and marinate for 2 hours (or overnight).','Preheat oven to 180°C fan (200°C without fan).','Slice onion into rings and wash the tomatoes. Remove beef from marinade.','Thread beef, onion and tomatoes alternately onto wooden skewers.','Place on an oven rack and bake for 7–10 minutes until cooked through.','Meanwhile make the sauce: melt butter in a small saucepan over low heat.','Add flour and stir until lightly golden.','Add 150 ml wine gradually, stirring as it comes to a gentle boil.','Add balsamic vinegar, a pinch of cinnamon and chilli. Stir until slightly thickened.','Pour sauce over skewers and serve immediately.'], ua: ['Приготуйте маринад: змішайте сіль, мед/еритритол, чилі та корицю. Додайте 150 мл вина. Залийте м’ясо та маринуйте 2 години (або на ніч).','Розігрійте духовку до 180°C з конвекцією (200°C без).','Наріжте цибулю кільцями та промийте помідори. Вийміть м’ясо з маринаду.','Почергово нанизайте м’ясо, цибулю та помідори на дерев’яні шпажки.','Запікайте на решітці 7–10 хвилин до готовності.','Тим часом приготуйте соус: розтопіть масло в сотейнику на слабкому вогні.','Додайте борошно та помішуйте до легкого золотистого кольору.','Поступово влийте 150 мл вина, помішуючи до легкого закипання.','Додайте бальзамічний оцет, по щіпці кориці та чилі. Помішуйте до легкого загустіння.','Полийте шашлики соусом і подавайте одразу.'] },
    note: { en: 'Replace honey with erythritol and wheat flour with almond flour to reduce the glycaemic impact of the sauce without changing the flavour.', ua: 'Замініть мед еритритолом, а пшеничне борошно — мигдалевим, щоб знизити глікемічний вплив соусу без зміни смаку.' }
  },
  {
    slug: 'lemon-thyme-cookies', img: '02-lemon-thyme-cookies.jpeg', cat: 'snack',
    tags: ['sugar-free', 'gluten-free', 'low-carb', 'vegetarian'],
    title: { en: 'Flour-free Lemon & Thyme Cookies', ua: 'Безборошняне печиво з лимоном та чебрецем' },
    meta: { prep: { en: '5 min + 30 min chilling', ua: '5 хв + 30 хв у холодильнику' }, cook: { en: '7 min', ua: '7 хв' }, serves: { en: 'Makes ~20', ua: '~20 штук' } },
    why: { en: 'Made entirely with almond flour instead of wheat — naturally low in carbohydrates and high in protein and healthy fats. Sweetened with stevia, so no blood sugar spike.', ua: 'Готується виключно на мигдалевому борошні замість пшеничного — мало вуглеводів, багато білка та корисних жирів. Підсолоджено стевією — без стрибків цукру.' },
    ingredients: { en: ['2 cups (200 g) almond flour','2 eggs','1 tsp vanilla extract','1 tbsp lemon juice','2 tsp lemon zest','1 tsp liquid stevia (or to taste)','¼ cup (60 ml) liquid coconut oil','1 tsp ground flaxseed','Small pinch of fresh or dried thyme'], ua: ['2 склянки (200 г) мигдалевого борошна','2 яйця','1 ч. л. ванільного екстракту','1 ст. л. лимонного соку','2 ч. л. лимонної цедри','1 ч. л. рідкої стевії (за смаком)','¼ склянки (60 мл) рідкої кокосової олії','1 ч. л. меленого льону','Невелика щіпка свіжого або сушеного чебрецю'] },
    method: { en: ['Mix all ingredients together until combined. Refrigerate the dough for 30 minutes.','Preheat oven to 180°C fan. Line a baking tray with baking paper.','Pinch off small pieces and roll into balls — the dough should hold its shape.','Place on the paper and press a few thyme leaves gently into the top of each.','Bake for 5–7 minutes until the edges are just lightly golden. Don’t overbake — they should stay slightly soft.'], ua: ['Змішайте всі інгредієнти. Поставте тісто в холодильник на 30 хвилин.','Розігрійте духовку до 180°C з конвекцією. Застеліть деко пергаментом.','Відщипуйте невеликі шматочки та формуйте кульки — тісто має тримати форму.','Викладіть на пергамент і злегка вдавіть кілька листочків чебрецю зверху.','Випікайте 5–7 хвилин до легкого золотистого краю. Не перетримуйте — печиво має залишатися трохи м’яким.'] },
    note: { en: 'These are low in carbs but high in fat and calories — keep portions to 2–3 cookies at a time.', ua: 'Печиво містить мало вуглеводів, але багато жирів і калорій — оптимальна порція 2–3 штуки.' }
  },
  {
    slug: 'cottage-cheese-poppy-bake', img: '03-cottage-cheese-poppy-bake.jpeg', cat: 'dessert',
    tags: ['sugar-free', 'gluten-free', 'low-carb', 'vegetarian'],
    title: { en: 'Sugar-free Cottage Cheese & Poppy Seed Bake', ua: 'Сирний десерт без цукру з маком' },
    meta: { prep: { en: '10 min', ua: '10 хв' }, cook: { en: '30 min', ua: '30 хв' }, serves: { en: 'Serves 2–3', ua: '2–3 порції' } },
    why: { en: 'High-protein cottage cheese with an almond-and-coconut-flour base — no refined sugar, no white flour. Peanut butter adds healthy fats that slow digestion and steady blood sugar.', ua: 'Сир, багатий на білок, з основою з мигдалевого й кокосового борошна — без цукру та білого борошна. Арахісова паста додає корисні жири, що сповільнюють засвоєння.' },
    ingredients: { en: ['250 g cottage cheese or quark (as dry as possible)','1 egg','1 tsp vanilla','¼ cup almond flour','1 tbsp coconut flour','½ cup natural peanut butter (unsweetened)','2 tbsp Truvia or erythritol','1 tbsp coconut oil (plus extra to grease)','3 tbsp poppy seeds'], ua: ['250 г сиру (кварку), якомога сухішого','1 яйце','1 ч. л. ваніліну','¼ склянки мигдалевого борошна','1 ст. л. кокосового борошна','½ склянки натуральної арахісової пасти (без цукру)','2 ст. л. Truvia або еритритолу','1 ст. л. кокосової олії (плюс для змащування)','3 ст. л. маку'] },
    method: { en: ['Grease a small tin (approx. 300–400 ml) with coconut oil. Preheat oven to 180°C.','Make the base: mix peanut butter with coconut oil and both flours until firm but workable. Add more coconut flour if too runny.','Press the base evenly into the bottom of the tin.','Make the filling: mix cottage cheese, sweetener, vanilla and egg until smooth.','Pour over the base and sprinkle poppy seeds evenly on top.','Bake at 180°C for 20–30 minutes depending on how wet the cheese is. Cool before slicing.'], ua: ['Змастіть невелику форму (300–400 мл) кокосовою олією. Розігрійте духовку до 180°C.','Приготуйте основу: змішайте арахісову пасту з кокосовою олією та обома видами борошна до щільної, але пластичної маси. Додайте кокосового борошна, якщо рідко.','Рівномірно розподіліть основу по дну форми.','Приготуйте начинку: змішайте сир, підсолоджувач, ванілін та яйце до однорідності.','Викладіть поверх основи та рівномірно посипте маком.','Випікайте при 180°C 20–30 хвилин залежно від вологості сиру. Охолодіть перед нарізанням.'] },
    note: { en: 'Use the driest cottage cheese or quark you can find — wetter varieties need a longer bake time.', ua: 'Використовуйте якомога сухіший сир — з вологішим десерт потребуватиме довшого запікання.' }
  },
  {
    slug: 'avocado-ice-cream', img: '04-avocado-ice-cream.jpg', cat: 'dessert',
    tags: ['sugar-free', 'gluten-free', 'low-carb', 'vegetarian', 'dairy-free'],
    title: { en: 'Avocado Ice Cream (No Sugar, 5 Ingredients)', ua: 'Морозиво з авокадо (без цукру, 5 інгредієнтів)' },
    meta: { prep: { en: '10 min', ua: '10 хв' }, cook: { en: 'Freeze 30 min', ua: 'Заморозка 30 хв' }, serves: { en: 'Serves 1–2', ua: '1–2 порції' } },
    why: { en: 'Avocado is one of the lowest-GI fruits — high in healthy monounsaturated fats with virtually no impact on blood sugar. No added sugar, only 5 ingredients.', ua: 'Авокадо — один із фруктів з найнижчим ГІ: багато корисних жирів і майже нульовий вплив на цукор. Без доданого цукру, лише 5 інгредієнтів.' },
    ingredients: { en: ['½ very ripe avocado','1 tbsp lemon juice','1 tsp powdered stevia (to taste)','1 tbsp coconut oil','Small pinch of vanilla'], ua: ['½ дуже стиглого авокадо','1 ст. л. лимонного соку','1 ч. л. стевії в порошку (за смаком)','1 ст. л. кокосової олії','Невелика щіпка ваніліну'] },
    method: { en: ['Blend all ingredients until completely smooth.','Pour into a small container and freeze for 30 minutes.','Remove and shape as desired. If too firm, transfer to the fridge for a few minutes to soften before serving.'], ua: ['Збийте всі інгредієнти у блендері до однорідності.','Перелийте в невелику ємність і заморозьте на 30 хвилин.','Вийміть та сформуйте за бажанням. Якщо надто тверде — потримайте в холодильнику кілька хвилин.'] },
    note: { en: "The avocado disappears completely into the texture — only the pale green colour remains. If you don't like avocado, you won't taste it at all.", ua: 'Смак авокадо у готовому морозиві не відчувається — залишається лише ніжна кремова текстура та блідо-зелений колір.' }
  },
  {
    slug: 'almond-pecan-cookies', img: '05-almond-pecan-cookies.jpeg', cat: 'snack',
    tags: ['sugar-free', 'gluten-free', 'low-carb', 'vegetarian'],
    title: { en: 'Almond & Pecan Cookies (No Flour, No Sugar)', ua: 'Мигдалево-пеканове печиво (без борошна, без цукру)' },
    meta: { prep: { en: '5 min', ua: '5 хв' }, cook: { en: '12 min', ua: '12 хв' }, serves: { en: 'Makes ~15', ua: '~15 штук' } },
    why: { en: 'Pure almond flour base with no refined sugar — sweetened only with erythritol. High in protein and healthy fats, low in carbohydrates. A reliable, fail-proof recipe.', ua: 'Основа — чисте мигдалеве борошно без рафінованого цукру, підсолоджене лише еритритолом. Багато білка та корисних жирів, мало вуглеводів. Простий безвідмовний рецепт.' },
    nutrition: { en: 'Per serving approx.: Carbs 10 g · Fat 41 g · Protein 19 g', ua: 'На порцію приблизно: Вуглеводи 10 г · Жири 41 г · Білки 19 г' },
    ingredients: { en: ['200 g almond flour','1 large egg','1 tsp vanilla extract','1 tbsp lime juice (plus zest of ½ lime)','½ tsp bicarbonate of soda','1½ tbsp Truvia or erythritol','A handful of pecan halves (one per cookie)'], ua: ['200 г мигдалевого борошна','1 велике яйце','1 ч. л. ванільного екстракту','1 ст. л. соку лайма (плюс цедра ½ лайма)','½ ч. л. харчової соди','1½ ст. л. Truvia або еритритолу','Жменя горіхів пекан (по одному на печиво)'] },
    method: { en: ['Zest half a lime and squeeze out the juice.','Mix all ingredients together — the dough should be elastic and slightly moist.','Preheat oven to 150°C and line a tray with baking paper.','Scoop out dough and roll into balls. Press one pecan half into the centre of each.','Bake for 10–12 minutes. They firm up as they cool — don’t worry if they seem soft in the oven.'], ua: ['Знімте цедру з половини лайма та видавіть сік.','Змішайте всі інгредієнти — тісто має бути еластичним і трохи вологим.','Розігрійте духовку до 150°C. Застеліть деко пергаментом.','Набирайте тісто та формуйте кульки. У центр кожної вдавіть половинку пекана.','Випікайте 10–12 хвилин. Охолоджуючись, печиво затвердіє.'] },
    note: { en: 'You can use walnut or hazelnut flour instead of almond flour — the result is just as good.', ua: 'Замість мигдалевого борошна можна взяти лісовий або волоський горіх — результат буде таким само вдалим.' }
  },
  {
    slug: 'carrot-cake-philadelphia', img: '06-carrot-cake-philadelphia.jpg', cat: 'dessert',
    tags: ['sugar-free', 'vegetarian'],
    title: { en: 'Carrot Cake with Philadelphia Cream (Sugar-free)', ua: 'Морквяний кекс без цукру з кремом Філадельфія' },
    meta: { prep: { en: '15 min', ua: '15 хв' }, cook: { en: '50 min', ua: '50 хв' }, serves: { en: 'Serves 8–10', ua: '8–10 порцій' } },
    why: { en: 'Wholegrain flour has a lower GI than white; erythritol replaces sugar entirely. Carrots add natural sweetness with fibre, and the Philadelphia frosting is protein-rich with no added sugar.', ua: 'Цільнозернове борошно має нижчий ГІ ніж пшеничне; еритритол замінює цукор. Морква додає природну солодкість і клітковину, а крем Філадельфія — білковий, без цукру.' },
    ingredients: { en: ['— CAKE —','300 g carrot, finely grated','200 g wholegrain wheat flour','65 g erythritol or Truvia','100 g butter, softened','5 eggs','1 tsp cinnamon','½ tsp nutmeg','2 tsp baking powder','1 tsp baking soda','1 tsp salt','1 tsp vanilla extract','— FROSTING —','200 g Philadelphia cream cheese','1 tbsp lemon juice','15 g erythritol or Truvia','½ tsp vanilla extract'], ua: ['— КЕКС —','300 г моркви, дрібно натертої','200 г цільнозернового пшеничного борошна','65 г еритритолу або Truvia','100 г вершкового масла, розм’якшеного','5 яєць','1 ч. л. кориці','½ ч. л. мускатного горіха','2 ч. л. розпушувача','1 ч. л. харчової соди','1 ч. л. солі','1 ч. л. ванільного екстракту','— КРЕМ —','200 г вершкового сиру Філадельфія','1 ст. л. лимонного соку','15 г еритритолу або Truvia','½ ч. л. ванільного екстракту'] },
    method: { en: ['Preheat oven to 180°C. Line a cake tin with parchment.','Beat softened butter with 65 g sweetener and vanilla until light and fluffy.','Add eggs one at a time, mixing well after each.','Sift together flour, cinnamon, nutmeg, baking powder, baking soda and salt. Fold into the wet mixture.','Stir in the grated carrot.','Pour into the tin and bake 40–50 minutes, until a skewer comes out clean. Cool completely before frosting.','For the frosting: beat Philadelphia with lemon juice, 15 g sweetener and vanilla until smooth.','Spread frosting over the cooled cake.'], ua: ['Розігрійте духовку до 180°C. Застеліть форму пергаментом.','Збийте розм’якшене масло з 65 г підсолоджувача та ваніллю до пишності.','Додавайте яйця по одному, добре перемішуючи.','Просійте борошно, корицю, мускатний горіх, розпушувач, соду та сіль. Вмішайте в основну суміш.','Додайте терту моркву та перемішайте.','Вилийте у форму та випікайте 40–50 хвилин (перевірте зубочисткою). Повністю охолодіть.','Для крему: збийте Філадельфію з лимонним соком, 15 г підсолоджувача та ваніллю до гладкості.','Намажте крем на охолоджений кекс.'] }
  },
  {
    slug: 'wholegrain-bread', img: '07-wholegrain-bread.jpeg', cat: 'bread',
    tags: ['sugar-free', 'vegetarian', 'dairy-free'],
    title: { en: 'Wholegrain Sourdough Bread', ua: 'Цільнозерновий хліб на заквасці' },
    meta: { prep: { en: '10 min + 10–16 h proving', ua: '10 хв + 10–16 год вистоювання' }, cook: { en: '40 min', ua: '40 хв' }, serves: { en: '10–12 slices', ua: '10–12 скибок' } },
    why: { en: 'Wholegrain flour retains bran and germ, slowing digestion. Sourdough fermentation further reduces GI compared to regular bread. Flaxseed adds omega-3 and fibre.', ua: 'Цільнозернове борошно зберігає висівки та зародок, уповільнюючи травлення. Ферментація закваски знижує ГІ. Лляне борошно збагачує омега-3 та клітковиною.' },
    ingredients: { en: ['250 g wholegrain wheat flour','20 g flaxseed flour','50 g sourdough starter (active)','5 g salt'], ua: ['250 г цільнозернового пшеничного борошна','20 г борошна з льону','50 г закваски (активної)','5 г солі'] },
    method: { en: ['Combine wholegrain wheat flour and flaxseed flour in a large bowl.','Add the starter and mix, adding a little water gradually until a rough dough forms.','Cover and rest at room temperature for 8–12 hours (overnight is ideal).','Add salt and fold the dough several times. Shape into a loaf.','Prove a further 2–4 hours until noticeably risen.','Preheat oven to 230°C. Bake covered (Dutch oven) for 20 minutes, then uncover and bake 20 minutes more until golden and hollow-sounding.','Cool on a wire rack before slicing — important for texture.'], ua: ['Змішайте цільнозернове та лляне борошно у великій мисці.','Додайте закваску та перемішайте, поступово вливаючи трохи води до утворення тіста.','Накрийте та залиште при кімнатній температурі на 8–12 годин (ідеально на ніч).','Додайте сіль та кілька разів складіть тісто. Сформуйте хлібину.','Залиште підходити ще 2–4 години до помітного збільшення.','Розігрійте духовку до 230°C. Перші 20 хвилин випікайте накритим (чавунець), потім відкрийте ще на 20 хвилин до золотистої скоринки.','Охолодіть на решітці перед нарізанням.'] }
  },
  {
    slug: 'pearl-barley-kutia', img: '08-pearl-barley-kutia.jpeg', cat: 'dessert',
    tags: ['dairy-free', 'vegetarian'],
    title: { en: 'Pearl Barley Kutia (Traditional Ukrainian Dish)', ua: 'Кутя з перлової крупи (традиційна різдвяна)' },
    meta: { prep: { en: '20 min + soaking', ua: '20 хв + замочування' }, cook: { en: '80 min', ua: '80 хв' }, serves: { en: 'Serves 8–10', ua: '8–10 порцій' } },
    why: { en: 'Pearl barley has one of the lowest GI values of all grains (GI ~25), thanks to its rich beta-glucan content. This traditional Ukrainian dish is naturally suited to blood sugar management.', ua: 'Перлова крупа має один із найнижчих ГІ серед зернових (ГІ ~25) завдяки бета-глюкану. Ця традиційна українська страва природно підходить для контролю цукру.' },
    ingredients: { en: ['600 g pearl barley','200 g raisins','100 g walnuts, roughly chopped','50 g poppy seeds','50 g honey or sweetener of choice'], ua: ['600 г перлової крупи','200 г родзинок','100 г волоських горіхів, крупно порубаних','50 г маку','50 г меду або підсолоджувача на вибір'] },
    method: { en: ['Rinse the barley thoroughly and soak in cold water for at least 1 hour (or overnight).','Cook in plenty of salted water for 60–80 minutes until tender. Drain and cool slightly.','Soak raisins in warm water for 10 minutes, then drain.','Pour boiling water over the poppy seeds, drain after 5 minutes, then grind or blend lightly.','Combine the barley with raisins, walnuts, poppy seeds and honey. Mix well.','Taste and adjust sweetness. Serve warm or at room temperature.'], ua: ['Добре промийте крупу та замочіть у холодній воді мінімум на 1 годину (або на ніч).','Варіть у підсоленій воді 60–80 хвилин до м’якості. Злийте воду, злегка охолодіть.','Замочіть родзинки у теплій воді на 10 хвилин, потім злийте.','Залийте мак окропом, через 5 хвилин злийте, злегка перетріть.','З’єднайте кашу з родзинками, горіхами, маком та медом. Добре перемішайте.','Скуштуйте та відрегулюйте солодкість. Подавайте теплою або кімнатної температури.'] }
  },
  {
    slug: 'pumpkin-muffins-halloween', img: '09-pumpkin-muffins-halloween.jpg', cat: 'baking',
    tags: ['sugar-free', 'vegetarian'],
    title: { en: 'Halloween Pumpkin Muffins (Sugar-free)', ua: 'Гарбузові маффіни до Хелловіну (без цукру)' },
    meta: { prep: { en: '10 min', ua: '10 хв' }, cook: { en: '25 min', ua: '25 хв' }, serves: { en: '12 muffins', ua: '12 маффінів' } },
    why: { en: 'Pumpkin purée is low-calorie with a moderate GI. Wholegrain flour and erythritol keep the glycaemic impact low, while cinnamon and ginger support blood sugar regulation.', ua: 'Гарбузове пюре низькокалорійне з помірним ГІ. Цільнозернове борошно та еритритол мінімізують глікемічне навантаження, а кориця й імбир допомагають регуляції цукру.' },
    ingredients: { en: ['2 cups wholegrain wheat flour','1 tsp gingerbread spice (ginger, cinnamon, clove, allspice)','1½ tsp baking powder','2 eggs','1 cup milk','1 cup pumpkin purée','¼ cup Truvia or erythritol','1 tbsp coconut oil, melted','1 tsp vanilla extract'], ua: ['2 склянки цільнозернового пшеничного борошна','1 ч. л. суміші прянощів для пряників (імбир, кориця, гвоздика, запашний перець)','1½ ч. л. розпушувача','2 яйця','1 склянка молока','1 склянка гарбузового пюре','¼ склянки Truvia або еритритолу','1 ст. л. кокосової олії, розтопленої','1 ч. л. ванільного екстракту'] },
    method: { en: ['Preheat oven to 180°C. Line a muffin tray with paper cases.','Whisk together flour, spice mix and baking powder.','Separately beat eggs, then add milk, pumpkin purée, sweetener, coconut oil and vanilla. Mix well.','Pour wet into dry and stir until just combined — do not over-mix.','Spoon into the cases, filling each about ¾ full.','Bake 20–25 minutes until a skewer comes out clean.','Cool in the tray for 5 minutes, then transfer to a wire rack.'], ua: ['Розігрійте духовку до 180°C. Застеліть форму паперовими вкладишами.','Збийте разом борошно, суміш прянощів та розпушувач.','Окремо збийте яйця, потім додайте молоко, гарбузове пюре, підсолоджувач, кокосову олію та ваніль.','Влийте рідке до сухого та перемішайте до рівномірності — не перемішуйте зайво.','Розкладіть по формах, заповнюючи на ¾.','Випікайте 20–25 хвилин (перевірте зубочисткою).','Охолодіть у формі 5 хвилин, потім перенесіть на решітку.'] }
  },
  {
    slug: 'lime-almond-dessert', img: '10-lime-almond-dessert.jpeg', cat: 'dessert',
    tags: ['sugar-free', 'gluten-free', 'vegetarian'],
    title: { en: 'Lime & Almond Dessert (Sugar-free)', ua: 'Лаймово-мигдалевий десерт (без цукру)' },
    meta: { prep: { en: '10 min', ua: '10 хв' }, cook: { en: '~30 min + chilling', ua: '~30 хв + охолодження' }, serves: { en: 'Serves 8', ua: '8 порцій' } },
    why: { en: 'Coconut and almond flour replace wheat, giving a low-carb, high-fibre base. Bananas provide natural sweetness; Truvia contains no sugar.', ua: 'Кокосове та мигдалеве борошно замінюють пшеничне — низьковуглеводна, багата клітковиною основа. Банани дають природну солодкість; Truvia без цукру.' },
    ingredients: { en: ['½ cup coconut flour','1 tbsp cinnamon','1 tsp baking soda','5 eggs','⅓ cup coconut oil','2 small ripe bananas','1 tbsp vanilla extract','Pinch of sea salt','1 cup almond flour','5 tbsp peanut butter','3 tbsp Truvia or erythritol','2½ limes (zest + juice)','100 g Greek yogurt'], ua: ['½ склянки кокосового борошна','1 ст. л. кориці','1 ч. л. харчової соди','5 яєць','⅓ склянки кокосової олії','2 невеликі стиглі банани','1 ст. л. ванільного екстракту','Дрібка морської солі','1 склянка мигдалевого борошна','5 ст. л. арахісового масла','3 ст. л. Truvia або еритритолу','2½ лайми (цедра + сік)','100 г грецького йогурту'] },
    method: { en: ['Preheat oven to 180°C. Line a tin with parchment, lightly greased.','Mix dry ingredients: coconut flour, cinnamon, baking soda, sea salt.','Blend eggs, mashed bananas, coconut oil, vanilla and juice of 1 lime until smooth.','Combine wet and dry. Pour into the tin and bake about 30 minutes.','Topping: mix almond flour, sweetener, remaining lime juice and peanut butter. Gradually add Greek yogurt to a spreadable consistency.','Trim the baked base if you like; crumble trimmings into the topping.','Spread the yogurt-almond layer over the base.','Scatter almond-peanut crumble on top. Cover and refrigerate — best served the next day.'], ua: ['Розігрійте духовку до 180°C. Застеліть форму пергаментом, злегка змастіть.','Змішайте сухі: кокосове борошно, корицю, соду, сіль.','Збийте яйця, розім’яті банани, кокосову олію, ваніль та сік 1 лайма до однорідності.','З’єднайте суміші. Вилийте у форму та випікайте близько 30 хвилин.','Топінг: змішайте мигдалеве борошно, підсолоджувач, сік решти лаймів та арахісове масло. Поступово додавайте йогурт до пластичності.','За бажання зріжте краї коржа; крихти додайте до топінгу.','Нанесіть йогуртово-мигдалевий шар на корж.','Посипте мигдально-арахісовою крихтою. Накрийте та поставте в холодильник — найсмачніший наступного дня.'] }
  },
  {
    slug: 'avocado-mayonnaise', img: '11-avocado-mayonnaise.jpg', cat: 'sauce',
    tags: ['sugar-free', 'gluten-free', 'low-carb', 'vegetarian'],
    title: { en: 'Avocado Mayonnaise (Sugar-free)', ua: 'Майонез з авокадо (без цукру)' },
    meta: { prep: { en: '1 min', ua: '1 хв' }, cook: { en: '4 min', ua: '4 хв' }, serves: { en: 'Serves 4–6', ua: '4–6 порцій' } },
    why: { en: 'Avocado is rich in monounsaturated fats and has virtually no sugar. This sauce has a GI close to zero — a perfect substitute for shop-bought mayonnaise.', ua: 'Авокадо багатий на корисні жири та майже не містить цукру. ГІ цього соусу близький до нуля — ідеальна заміна магазинному майонезу.' },
    ingredients: { en: ['1 very ripe avocado','2 tsp lemon juice','1 tsp Dijon mustard','½ tsp salt (mustard already contains salt — adjust)','½ tsp dried garlic powder','½ tsp dried onion powder','¼ cup Greek yogurt'], ua: ['1 дуже стиглий авокадо','2 ч. л. лимонного соку','1 ч. л. діжонської гірчиці','½ ч. л. солі (в гірчиці вже є сіль — регулюйте)','½ ч. л. часникового порошку','½ ч. л. цибульного порошку','¼ склянки грецького йогурту'] },
    method: { en: ['Blend avocado with a little Greek yogurt on low speed until smooth.','Add all remaining ingredients and blend on high speed until completely silky.'], ua: ['Збийте авокадо з невеликою кількістю йогурту на малих обертах до однорідності.','Додайте всі інші інгредієнти та збийте на великих обертах до повної гладкості.'] },
    note: { en: 'Store in a sealed glass jar in the fridge for 2–3 days. It darkens slightly — refresh with a splash of lemon juice before serving.', ua: 'Зберігайте в закритій скляній банці в холодильнику 2–3 дні. Соус трохи темніє — перед подачею освіжте лимонним соком.' }
  },
  {
    slug: 'oat-cookies-coconut-sugar', img: '12-oat-cookies-coconut-sugar.jpg', cat: 'baking',
    tags: ['vegetarian'],
    title: { en: 'Oat Cookies with Coconut Sugar', ua: 'Вівсяне печиво на кокосовому цукрі' },
    meta: { prep: { en: '10 min', ua: '10 хв' }, cook: { en: '30 min', ua: '30 хв' }, serves: { en: 'Makes ~18', ua: '~18 штук' } },
    why: { en: 'Coconut sugar has a lower GI than regular sugar (GI ~35 vs 70). Swap for erythritol with a few drops of stevia to reduce GI further. Coarse oats digest slowly, giving lasting energy.', ua: 'Кокосовий цукор має нижчий ГІ ніж звичайний (~35 проти 70). Замініть на еритритол зі стевією для ще нижчого ГІ. Крупні вівсяні пластівці перетравлюються повільно.' },
    ingredients: { en: ['1 cup rolled oats (coarse / old-fashioned)','1 cup wholegrain wheat flour','⅓ cup coconut sugar (or erythritol for lower GI)','130 g butter or coconut oil','1 egg','Pinch of sea salt','Pinch of baking powder','Pinch of vanilla','Pinch of cinnamon'], ua: ['1 склянка вівсяних пластівців (крупного помелу)','1 склянка цільнозернового пшеничного борошна','⅓ склянки кокосового цукру (або еритритол для нижчого ГІ)','130 г вершкового або кокосового масла','1 яйце','Дрібка морської солі','Дрібка розпушувача','Дрібка ваніліну','Дрібка кориці'] },
    method: { en: ['In a mixer, combine softened butter, egg and coconut sugar on low speed.','Add all remaining ingredients. Use the paddle (not the blade) so the oats stay whole.','Line a baking sheet with parchment. Preheat oven to 190°C.','Refrigerate the dough 10 minutes. Roll into balls and flatten gently with the base of a glass.','Bake 20 minutes until golden. Cool on the tray — cookies firm up as they cool.'], ua: ['У міксері змішайте розм’якшене масло, яйце та кокосовий цукор на малих обертах.','Додайте решту інгредієнтів. Використовуйте лопатку (не ніж), щоб пластівці лишились цілими.','Застеліть деко пергаментом. Розігрійте духовку до 190°C.','Охолодіть тісто 10 хвилин. Скочуйте кульки та приплющуйте дном склянки.','Випікайте 20 хвилин до золотистого кольору. Остигаючи, печиво твердіє.'] }
  },
  {
    slug: 'lemon-cookies-coconut-sugar', img: '13-lemon-cookies-coconut-sugar.jpg', cat: 'baking',
    tags: ['vegetarian', 'dairy-free'],
    title: { en: 'Lemon Cookies with Coconut Sugar', ua: 'Лимонне печиво на кокосовому цукрі' },
    meta: { prep: { en: '10 min + 30 min chilling', ua: '10 хв + 30 хв у холодильнику' }, cook: { en: '15 min', ua: '15 хв' }, serves: { en: 'Makes ~16', ua: '~16 штук' } },
    why: { en: 'A blend of flaxseed flour, coconut flour and wholegrain flour replaces refined white flour. Coconut sugar replaces refined sugar.', ua: 'Суміш лляного, кокосового та цільнозернового борошна замінює рафіноване біле борошно. Кокосовий цукор замінює звичайний.' },
    ingredients: { en: ['1 tbsp lemon zest','½ cup wholegrain wheat flour','45 g coconut oil or butter','1 tsp baking powder','2 tbsp flaxseed flour','2 tbsp coconut flour','50 g coconut sugar','4 tbsp lemon juice'], ua: ['1 ст. л. лимонної цедри','½ склянки цільнозернового пшеничного борошна','45 г кокосового або вершкового масла','1 ч. л. розпушувача','2 ст. л. борошна з льону','2 ст. л. кокосового борошна','50 г кокосового цукру','4 ст. л. лимонного соку'] },
    method: { en: ['Combine all ingredients in a processor using the paddle (not the blade). The dough will be crumbly and slightly loose.','Refrigerate for 30 minutes. Preheat oven to 180°C towards the end.','Line a baking sheet with parchment.','If still too soft, mix in 1–2 tsp extra flaxseed flour. Roll into balls and flatten with a glass.','Bake for 15 minutes — golden but not burnt.','Cool fully. Cookies firm up significantly as they cool.'], ua: ['Змішайте всі інгредієнти в комбайні лопаткою (не ножем). Тісто буде розсипчастим.','Поставте в холодильник на 30 хвилин. Ближче до кінця розігрійте духовку до 180°C.','Застеліть деко пергаментом.','Якщо тісто м’яке — додайте 1–2 ч. л. лляного борошна. Скочуйте кульки та приплющуйте склянкою.','Випікайте 15 хвилин — золотисті, але не підгорілі.','Повністю охолодіть. Остигаючи, печиво сильно твердіє.'] }
  },
  {
    slug: 'lviv-cheesecake', img: '14-lviv-cheesecake.jpg', cat: 'dessert',
    tags: ['gluten-free', 'vegetarian'],
    title: { en: 'Lviv Cheesecake (Lvivsky Syrnyk)', ua: 'Львівський сирник' },
    meta: { prep: { en: '10 min', ua: '10 хв' }, cook: { en: '20 min + overnight', ua: '20 хв + ніч у холодильнику' }, serves: { en: 'Serves 10–12', ua: '10–12 порцій' } },
    why: { en: 'The base is cottage cheese — high protein, no flour. Coconut flour adds fibre. The chocolate glaze uses cocoa butter and minimal sugar rather than milk chocolate.', ua: 'Основа — кисломолочний сир (білок, без борошна). Кокосове борошно додає клітковину. Шоколадна глазур — з какао-масла та мінімум цукру, без плитки шоколаду.' },
    ingredients: { en: ['— CHEESECAKE —','5 eggs','500 g cottage cheese or quark (squeeze out excess moisture)','1 handful raisins','30 g coconut flour','80 g sugar or sweetener of choice','Pinch of vanilla','1 tsp xanthan gum (optional)','— GLAZE —','1 tbsp cocoa butter','1 tbsp sugar','3 tbsp sour cream','2 tbsp cocoa powder'], ua: ['— СИРНИК —','5 яєць','500 г кисломолочного сиру або кварку (відтиснути зайву вологу)','1 жменя родзинок','30 г кокосового борошна','80 г цукру або підсолоджувача','Дрібка ваніліну','1 ч. л. ксантанової камеді (за бажанням)','— ГЛАЗУР —','1 ст. л. какао-масла','1 ст. л. цукру','3 ст. л. сметани','2 ст. л. какао-порошку'] },
    method: { en: ['Preheat oven to 190°C.','In a mixer with the paddle, combine cottage cheese, eggs, 80 g sugar, vanilla and raisins. Don’t use the blade — you want texture, not a smooth cream.','While mixing, gradually add coconut flour until you get a thick, sticky mass that holds its shape.','Grease a tin and line with parchment.','Transfer to the tin, smooth the top with a fork and bake for 20 minutes.','Cool completely before glazing.','Glaze: melt cocoa butter, then stir in sour cream, sugar and cocoa powder. Pour over immediately — it sets quickly.','Refrigerate overnight. Slice in the morning.'], ua: ['Розігрійте духовку до 190°C.','У міксері з лопаткою змішайте сир, яйця, 80 г цукру, ванілін та родзинки. Ніж не використовуйте — потрібна текстура, а не крем.','Продовжуючи заважати, поступово всипайте кокосове борошно до густої липкої маси.','Змастіть форму та застеліть пергаментом.','Викладіть масу, розрівняйте виделкою та випікайте 20 хвилин.','Повністю охолодіть перед глазур’ю.','Глазур: розтопіть какао-масло, додайте сметану, цукор та какао. Відразу полийте — глазур швидко застигає.','Поставте в холодильник на ніч. Зранку можна їсти.'] }
  },
  {
    slug: 'chocolate-ice-cream', img: '15-chocolate-ice-cream.jpg', cat: 'dessert',
    tags: ['sugar-free', 'gluten-free', 'low-carb', 'vegetarian'],
    title: { en: 'Sugar-free Chocolate Ice Cream', ua: 'Шоколадне морозиво без цукру' },
    meta: { prep: { en: '2 min', ua: '2 хв' }, cook: { en: '8 min + 3 h freezing', ua: '8 хв + 3 год заморозки' }, serves: { en: 'Serves 4', ua: '4 порції' } },
    why: { en: 'Sweetened entirely with stevia (GI = 0). Cocoa butter and butter provide slow-release fat. A blood-sugar-friendly chocolate fix with no added sugar.', ua: 'Підсолоджено виключно стевією (ГІ = 0). Какао-масло та вершкове масло дають повільне вивільнення енергії. Шоколадне задоволення без стрибка цукру.' },
    ingredients: { en: ['30 g cocoa butter','20 g butter','1 tsp liquid stevia (or 2 tbsp honey / sweetener)','½ cup milk','Pinch of vanilla','1 tbsp cocoa powder'], ua: ['30 г какао-масла','20 г вершкового масла','1 ч. л. рідкої стевії (або 2 ст. л. меду / підсолоджувача)','½ склянки молока','Дрібка ваніліну','1 ст. л. какао-порошку'] },
    method: { en: ['Melt cocoa butter in a microwave on full power for 30–40 seconds. If pieces remain, leave 5 minutes to finish melting.','Stir cocoa powder into the melted cocoa butter until completely smooth.','Combine milk, butter, stevia and vanilla, then stir in the cocoa-butter mixture. Mix thoroughly.','Pour into lolly moulds or small containers and freeze for at least 3 hours.'], ua: ['Розтопіть какао-масло в мікрохвильовій печі 30–40 секунд. Якщо лишились шматочки — дайте постояти 5 хвилин.','Додайте какао-порошок та ретельно розмішайте до однорідності.','З’єднайте молоко, масло, стевію та ванілін, потім вмішайте какао-масляну суміш.','Розлийте по формочках і поставте в морозильник мінімум на 3 години.'] }
  },
  {
    slug: 'vegetable-quiche-no-flour', img: '16-vegetable-quiche-no-flour.jpg', cat: 'main',
    tags: ['gluten-free', 'vegetarian'],
    title: { en: 'Vegetable Quiche without Flour', ua: 'Кіш з овочами без борошна' },
    meta: { prep: { en: '2 min', ua: '2 хв' }, cook: { en: '15–23 min', ua: '15–23 хв' }, serves: { en: 'Serves 3', ua: '3 порції' } },
    why: { en: 'No pastry, no flour — the base is egg and flaxseed. Feta adds protein and fat to slow glucose absorption. A light, nutrient-dense meal ready in under 25 minutes.', ua: 'Без тіста та борошна — основа з яєць і лляного борошна. Фета додає білок та жири, сповільнюючи засвоєння глюкози. Легка та поживна страва менш ніж за 25 хвилин.' },
    nutrition: { en: 'Per serving: Protein 12 g · Fat 11 g · Carbs 26 g', ua: 'На порцію: Білки 12 г · Жири 11 г · Вуглеводи 26 г' },
    ingredients: { en: ['6 eggs','2 onions','2 tbsp flaxseed flour','50 g bell pepper','180 g feta cheese','1 garlic clove','1 handful fresh spinach'], ua: ['6 яєць','2 цибулини','2 ст. л. борошна з льону','50 г солодкого перцю','180 г сиру фета','1 зубчик часнику','1 жменя свіжого шпинату'] },
    method: { en: ['Whisk eggs together with flaxseed flour in a large bowl.','Slice onions into rings or half-rings. Crush the garlic.','Add bell pepper, feta and spinach and mix by hand. Crumble the feta or cut into cubes.','Pour into a prepared tin and bake at 180°C for 15 minutes until set and golden on top.'], ua: ['Збийте яйця з лляним борошном виделкою у великій мисці.','Наріжте цибулю кільцями або напівкільцями. Часник пропустіть через давилку.','Додайте перець, фету та шпинат і перемішайте руками. Фету розкришіть або наріжте кубиками.','Вилийте у форму та запікайте при 180°C 15 хвилин до золотистої скоринки.'] }
  }
];
