// Pre-render SPA routes to real static HTML files for SEO.
//
// Why: the app is a client-rendered SPA. Every route except "/" and the
// pre-rendered blog posts is served by GitHub Pages' 404 fallback (HTTP 404 +
// JS redirect), and all SEO tags live in <helmet> inside <body>, applied only
// by JavaScript. So without JS — social scrapers, some crawlers — no page has
// a title, description, canonical or Open Graph tags.
//
// This script writes a real <route>/index.html for each route: the pristine,
// fully-interactive app shell (template untouched, so it boots identically)
// with correct per-route SEO tags injected into the real <head>, plus an
// absolute /support.js path. Result: HTTP 200 + crawler-visible SEO on every
// route, with interactivity preserved.
//
// Run:  node prerender.mjs        (regenerate all route files)
//
// Add a resource: add an entry to ROUTES below, then run this script.

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname));
const ORIGIN = 'https://lenafilatova.co.uk';
const BRAND = 'Lena Filatova';
const DEF_IMG = '/images/lena-filatova-womens-health-coach-over-40.jpg';

// One entry per route to pre-render. `dir` is the output directory (the file is
// written as <dir>/index.html). Home (index.html) is handled separately below.
const ROUTES = [
  { dir: 'about', path: '/about',
    title: `About ${BRAND} — women's health writer & coach living with type 1 diabetes`,
    desc: `Meet Lena Filatova — evidence-based writer and coach on women's health after 40, living with type 1 diabetes for over two decades. Diabetes, insulin resistance and perimenopause.` },
  { dir: 'shop', path: '/shop',
    title: `Digital products — ${BRAND}`,
    desc: `Guides, meal plans and 1:1 coaching designed for women over 40 — evidence-based support for nutrition, perimenopause and blood sugar.` },
  { dir: 'contact', path: '/contact',
    title: `Work with me — ${BRAND}`,
    desc: `Tell me where you are and what you'd like to change. I'll reply with how I can help and the best next step for you.` },
  { dir: 'resources', path: '/resources',
    title: `Tools & guides — ${BRAND}`,
    desc: `Practical, evidence-based resources to support women's health after 40 — free to use, no strings.` },
  { dir: 'resources/food-calculator', path: '/resources/food-calculator',
    title: `Metabolic food calculator — ${BRAND}`,
    desc: `A free food calculator that estimates how meals affect your blood sugar and metabolism — practical guidance for women's health after 40.` },
  { dir: 'resources/aid-comparison', path: '/resources/aid-comparison',
    title: `AID (Automated Insulin Delivery) system comparison 2026 — ${BRAND}`,
    desc: `A clear 2026 comparison of automated insulin delivery (AID) systems and insulin pumps, for people managing type 1 diabetes.` },
];

const esc = s => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

// Markers around the auto-generated block so re-runs are idempotent.
const MARK_START = '<!-- prerender:head (auto-generated by prerender.mjs — do not edit) -->';
const MARK_END = '<!-- /prerender:head -->';

// Build the SEO <head> block for a route.
function seoHead({ title, desc, canonical, image = DEF_IMG, type = 'website' }) {
  const t = esc(title), d = esc(desc), u = esc(canonical), img = esc(ORIGIN + image);
  return [MARK_START,
    `<title>${t}</title>`,
    `<meta name="description" content="${d}">`,
    `<link rel="canonical" href="${u}">`,
    `<meta property="og:type" content="${type}">`,
    `<meta property="og:site_name" content="${BRAND}">`,
    `<meta property="og:title" content="${t}">`,
    `<meta property="og:description" content="${d}">`,
    `<meta property="og:url" content="${u}">`,
    `<meta property="og:image" content="${img}">`,
    `<meta name="twitter:card" content="summary_large_image">`,
    `<meta name="twitter:title" content="${t}">`,
    `<meta name="twitter:description" content="${d}">`,
    `<meta name="twitter:image" content="${img}">`,
    MARK_END,
  ].map(l => '  ' + l).join('\n');
}

const ANCHOR = '<script src="./support.js"></script>';
// Read index.html and strip any previously-injected block so re-runs are clean.
let shell = await readFile(path.join(ROOT, 'index.html'), 'utf8');
const reEsc = s => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
shell = shell.replace(new RegExp('\\s*' + reEsc(MARK_START) + '[\\s\\S]*?' + reEsc(MARK_END), 'g'), '');

// The SEO tags live in <helmet> (inside <body>) and are copied into <head> by
// JS. If we also inject them into the real <head>, the runtime ends up with two
// (conflicting) titles/canonicals. So SEO belongs in the real <head> only:
// strip these tags from the template. syncSeo() reads/updates <head> directly,
// so nothing depends on them living in <helmet>. Fonts, styles, JSON-LD, PWA
// icons and the redirect script stay put.
shell = shell
  .replace(/\n[ \t]*<title>[\s\S]*?<\/title>/i, '')
  .replace(/\n[ \t]*<meta name="description"[^>]*>/i, '')
  .replace(/\n[ \t]*<link rel="canonical"[^>]*>/i, '')
  .replace(/\n[ \t]*<meta property="og:[^"]*"[^>]*>/gi, '')
  .replace(/\n[ \t]*<meta name="twitter:[^"]*"[^>]*>/gi, '');
if (!shell.includes(ANCHOR)) throw new Error('support.js anchor not found in index.html');

const written = [];

for (const r of ROUTES) {
  const head = seoHead({ title: r.title, desc: r.desc, canonical: ORIGIN + r.path });
  // Inject SEO into the real <head> and make support.js absolute (subdir-safe).
  const html = shell.replace(ANCHOR, `${head}\n<script src="/support.js"></script>`);
  const outDir = path.join(ROOT, r.dir);
  await mkdir(outDir, { recursive: true });
  await writeFile(path.join(outDir, 'index.html'), html);
  written.push(`${r.dir}/index.html`);
}

// Home: index.html's real <head> currently has no SEO tags — add them (keep the
// relative ./support.js since index.html is served at the root).
{
  const head = seoHead({
    title: `Lena Filatova — Evidence-based women's health after 40`,
    desc: `Evidence-based women's health after 40 — clear, practical guidance on diabetes, insulin resistance and perimenopause, plus a free newsletter and journal from Lena Filatova.`,
    canonical: ORIGIN + '/',
  });
  const home = shell.replace(ANCHOR, `${head}\n${ANCHOR}`);
  await writeFile(path.join(ROOT, 'index.html'), home);
  written.push('index.html (home <head> SEO)');
}

console.log('Generated:\n' + written.map(w => '  ' + w).join('\n'));
